import { GradeSpec } from './curriculum';

export const grade6: GradeSpec = {
  number: 6,
  name: 'Class 6',
  level_label: 'ATL Tinkering Level I',
  description: 'Foundation of tinkering: basic electronics, mechanics, 3D design, data visualization and design thinking.',
  modules: [
    {
      title: 'Basic Electronics',
      slug: 'basic-electronics',
      icon: '⚡',
      color: '#f72585',
      description: 'Learn how electricity flows and build your first circuits.',
      chapters: [
        {
          title: 'Paper Circuits',
          difficulty: 'beginner', est: 60,
          summary: 'Build a glowing circuit on paper using copper tape, an LED and a coin cell.',
          hook: 'What if a flat sheet of paper could light up like a greeting card that glows? With a paper circuit, it can!',
          layman: 'Electricity is like water flowing through a pipe. A paper circuit is a tiny "road" drawn with copper tape on paper. When you connect a battery, electricity travels along this road and lights up a small bulb called an LED. No road = no light.',
          concept: 'A circuit is a closed loop that lets electric current flow from the + terminal of a battery, through a component (like an LED), and back to the − terminal. Break the loop and the flow stops.',
          howItWorks: [
            'A coin cell battery pushes electric charge out of its positive (+) side.',
            'Copper tape acts as the wire/road carrying the charge.',
            'The LED only lights when its long leg (+) connects toward the battery + side (LEDs are one-way).',
            'The charge returns to the negative (−) side, completing the loop.',
            'A fold of paper can act as a switch: press to connect, release to break.',
          ],
          realWorld: [
            'Musical greeting cards that light up or play a tune.',
            'The wiring behind a light switch in your home.',
            'Decorative LED festival lights (diyas/string lights).',
          ],
          logic: 'Think in terms of "complete vs broken loop". If the LED does not glow, debug like a computer: check each connection one by one (battery polarity → tape continuity → LED direction). This is exactly how engineers trace faults.',
          steps: [
            'Draw a simple path on paper from battery to LED and back.',
            'Stick copper tape along the path, keeping corners folded (not cut).',
            'Place the LED with long leg toward battery +.',
            'Tape the coin cell down; press to test.',
            'Add a paper-fold switch to turn it on/off.',
          ],
          diagram: 'circuit',
          facts: [
            'LED stands for Light Emitting Diode and can last over 25,000 hours.',
            'A coin cell (CR2032) gives about 3 volts — just enough for most LEDs.',
            'Copper is used because it is one of the best, cheapest conductors of electricity.',
          ],
          questions: [
            { qtype: 'mcq', prompt: 'What is needed for an LED in a paper circuit to glow?', options: ['A broken loop', 'A complete (closed) circuit', 'Only paper', 'No battery'], answer: 'A complete (closed) circuit', explanation: 'Current flows only when the loop is closed.', difficulty: 'beginner' },
            { qtype: 'mcq', prompt: 'Why does the LED only light one way?', options: ['It is broken', 'LEDs allow current in one direction only', 'Paper blocks current', 'Batteries have no direction'], answer: 'LEDs allow current in one direction only', explanation: 'An LED is a diode — a one-way valve for current.', difficulty: 'intermediate' },
            { qtype: 'oneliner', prompt: 'In one line: what does copper tape do in a paper circuit?', answer: 'It carries the electric current like a wire.', explanation: 'Copper is a conductor.', difficulty: 'beginner' },
            { qtype: 'computational', prompt: 'A CR2032 gives 3V. An LED needs ~2V. Is 3V enough to light it?', options: ['Yes', 'No'], answer: 'Yes', explanation: '3V is greater than 2V, so it works (a resistor protects it).', difficulty: 'beginner' },
            { qtype: 'logical', prompt: 'The LED does not glow. You checked the battery is good. What should you check NEXT first?', options: ['Buy a new LED', 'Check LED direction and tape continuity', 'Throw the paper', 'Add more LEDs'], answer: 'Check LED direction and tape continuity', explanation: 'Debug step by step before replacing parts.', difficulty: 'intermediate' },
            { qtype: 'brain_teaser', prompt: 'You have one battery and two LEDs but want both to glow at full brightness. How should you connect them and why?', answer: 'Connect them in parallel so each gets the full voltage.', explanation: 'Parallel gives each LED the same voltage.', difficulty: 'advanced' },
            { qtype: 'tinkering', prompt: 'Design a paper greeting card that lights up only when it is opened. Describe your switch mechanism.', answer: 'Open-ended', explanation: 'A fold/flap that connects the tape when opened acts as a switch.', difficulty: 'advanced' },
          ],
        },
        {
          title: 'Introduction to Breadboard',
          difficulty: 'beginner', est: 60,
          summary: 'Understand the breadboard — the reusable playground for building circuits without soldering.',
          hook: 'How do engineers test ideas in minutes without glue or solder? They use a magical board full of hidden connections.',
          layman: 'A breadboard is like LEGO for electronics. It has many small holes. Some holes are secretly connected inside. You just push components in and they connect — no soldering, fully reusable.',
          concept: 'A breadboard has power rails (long lines, usually red +/blue −) running along the sides, and terminal strips in the middle where each row of 5 holes is connected. The central gap separates the two halves.',
          howItWorks: [
            'The two long side lines are power rails: one for + and one for −.',
            'In the middle, each horizontal row of 5 holes is internally connected.',
            'The notch/gap in the middle splits left and right — useful for chips.',
            'You build a circuit by sharing rows between component legs.',
          ],
          realWorld: [
            'Prototyping new gadgets before manufacturing.',
            'School science projects and robotics clubs.',
            'Testing a sensor before adding it to a product.',
          ],
          logic: 'A breadboard teaches "abstraction": you don\'t see the wires, but you reason about which holes are connected. Mapping invisible connections is the same skill used to read data structures in programming.',
          steps: [
            'Identify the + and − power rails.',
            'Connect a battery/USB power to the rails.',
            'Place an LED across two different rows.',
            'Add a resistor in series to protect the LED.',
            'Connect to power and watch it glow.',
          ],
          diagram: 'flow',
          facts: [
            'Breadboards got their name from real bread boards people once used to nail circuits onto.',
            'A standard breadboard has holes spaced 2.54 mm (0.1 inch) apart.',
            'No soldering means you can reuse the same parts hundreds of times.',
          ],
          questions: [
            { qtype: 'mcq', prompt: 'On a breadboard, the long side lines are used for?', options: ['Decoration', 'Power rails (+ and −)', 'Nothing', 'Only LEDs'], answer: 'Power rails (+ and −)', explanation: 'Side rails distribute power.', difficulty: 'beginner' },
            { qtype: 'mcq', prompt: 'How many holes are typically connected together in one middle row segment?', options: ['2', '5', '10', 'All of them'], answer: '5', explanation: 'Each terminal strip segment connects 5 holes.', difficulty: 'intermediate' },
            { qtype: 'oneliner', prompt: 'One line: why is a breadboard called "solderless"?', answer: 'Because parts just push in and connect without soldering.', explanation: 'Spring clips hold the legs.', difficulty: 'beginner' },
            { qtype: 'logical', prompt: 'Two LED legs are in the SAME 5-hole row. Are they connected?', options: ['Yes', 'No'], answer: 'Yes', explanation: 'Holes in the same terminal segment are joined.', difficulty: 'beginner' },
            { qtype: 'brain_teaser', prompt: 'Why is there a gap (notch) in the middle of the breadboard?', answer: 'So integrated-circuit chips can straddle it with pins on both sides not shorting.', explanation: 'The gap separates the two halves.', difficulty: 'advanced' },
            { qtype: 'tinkering', prompt: 'Plan a breadboard layout for 3 LEDs that can be switched on independently. Sketch your rows.', answer: 'Open-ended', explanation: 'Each LED needs its own switch row.', difficulty: 'advanced' },
          ],
        },
        {
          title: 'Series and Parallel Circuits',
          difficulty: 'intermediate', est: 60,
          summary: 'Discover two fundamental ways to connect components and how brightness changes.',
          hook: 'Why do some fairy lights all go dark when one bulb fails, while others keep glowing? The secret is series vs parallel!',
          layman: 'In a SERIES circuit, components sit in a single line — like people holding hands in one chain. In a PARALLEL circuit, each component has its own path — like separate lanes on a road.',
          concept: 'Series: one path for current; if it breaks anywhere, everything stops; voltage is shared. Parallel: multiple paths; each branch gets full voltage; if one breaks, others still work.',
          howItWorks: [
            'Series: current is the same everywhere, but voltage divides among components.',
            'Adding more bulbs in series makes each dimmer (voltage shared).',
            'Parallel: each branch gets full battery voltage, so bulbs stay bright.',
            'Parallel draws more current from the battery (it drains faster).',
          ],
          realWorld: [
            'Old fairy lights (series) — one dead bulb kills the string.',
            'Home wiring (parallel) — switching off the fan doesn’t turn off the light.',
            'Torch with multiple LEDs wired in parallel for brightness.',
          ],
          logic: 'This is a trade-off problem: series saves battery but is fragile; parallel is robust but power-hungry. Choosing between them is an optimization decision — exactly how engineers weigh pros and cons.',
          steps: [
            'Build a 2-LED series circuit and note the brightness.',
            'Rebuild the same 2 LEDs in parallel and compare.',
            'Remove one LED in each case and observe what happens.',
          ],
          diagram: 'series_parallel',
          facts: [
            'Your home uses parallel wiring so each device works independently.',
            'In series, total resistance adds up; in parallel, it drops.',
            'Christmas lights now use clever wiring so the string survives a dead bulb.',
          ],
          questions: [
            { qtype: 'mcq', prompt: 'In which circuit does one broken bulb stop all the others?', options: ['Parallel', 'Series', 'Neither', 'Both equally'], answer: 'Series', explanation: 'Series has a single shared path.', difficulty: 'beginner' },
            { qtype: 'mcq', prompt: 'Home wiring uses which type so devices work independently?', options: ['Series', 'Parallel', 'Random', 'No wiring'], answer: 'Parallel', explanation: 'Each device gets full voltage.', difficulty: 'beginner' },
            { qtype: 'oneliner', prompt: 'One line: what stays the same throughout a series circuit?', answer: 'The current is the same everywhere in series.', explanation: 'Single path → same current.', difficulty: 'intermediate' },
            { qtype: 'computational', prompt: 'Two equal bulbs share 3V in series. Roughly how much voltage does each get?', options: ['3V', '1.5V', '6V', '0V'], answer: '1.5V', explanation: 'Voltage divides equally between equal bulbs.', difficulty: 'intermediate' },
            { qtype: 'logical', prompt: 'You want maximum brightness for 3 LEDs from one battery. Which wiring?', options: ['Series', 'Parallel'], answer: 'Parallel', explanation: 'Each LED gets full voltage in parallel.', difficulty: 'intermediate' },
            { qtype: 'brain_teaser', prompt: 'A battery lasts longer with series wiring but bulbs are dim. How could you get both long life AND decent brightness?', answer: 'Use efficient LEDs and a balanced mix, or a higher-capacity battery.', explanation: 'Engineering is about balancing trade-offs.', difficulty: 'advanced' },
            { qtype: 'tinkering', prompt: 'Design a desk lamp where one switch dims and another brightens using series/parallel ideas.', answer: 'Open-ended', explanation: 'Switching paths changes brightness.', difficulty: 'advanced' },
          ],
        },
        {
          title: 'Traffic Light Circuit with Switch',
          difficulty: 'intermediate', est: 60,
          summary: 'Build a mini traffic signal using red, yellow and green LEDs controlled by switches.',
          hook: 'Ever wondered how traffic lights decide who goes and who stops? You can build your own pocket-sized traffic controller!',
          layman: 'A traffic light is just three LEDs (red, yellow, green) that turn on at the right time. With switches you control which light glows — and you start to think about timing and sequences.',
          concept: 'Each LED is an output; each switch is an input. By controlling which switch closes, you control which output turns on — the basis of all control systems.',
          howItWorks: [
            'Each LED connects to the battery through its own switch and resistor.',
            'Closing a switch completes that LED’s loop and it lights up.',
            'A correct traffic sequence is Red → Green → Yellow → Red.',
            'Later, a microcontroller can replace switches to automate timing.',
          ],
          realWorld: [
            'Real road traffic signals at intersections.',
            'Pedestrian crossing signals.',
            'Status lights on machines (red=stop, green=run).',
          ],
          logic: 'A traffic light is a state machine: it moves through fixed states in order. Writing the sequence Red→Green→Yellow→Red is your first taste of algorithms — a precise list of steps.',
          steps: [
            'Wire three LEDs each with its own switch and resistor.',
            'Test each switch lights only its own LED.',
            'Manually perform the Red→Green→Yellow sequence.',
            'Discuss how a timer could automate it.',
          ],
          diagram: 'flow',
          facts: [
            'The first electric traffic light was installed in 1914 in Cleveland, USA.',
            'Red was chosen for "stop" because it travels far and is easy to see.',
            'Modern signals use sensors to detect waiting vehicles.',
          ],
          questions: [
            { qtype: 'mcq', prompt: 'In the traffic light circuit, the switch acts as the?', options: ['Output', 'Input/control', 'Battery', 'Resistor'], answer: 'Input/control', explanation: 'Switches are inputs controlling outputs (LEDs).', difficulty: 'beginner' },
            { qtype: 'mcq', prompt: 'Correct safe sequence of a traffic light is?', options: ['Red→Green→Yellow→Red', 'Green→Red→Green', 'Yellow only', 'Random'], answer: 'Red→Green→Yellow→Red', explanation: 'Yellow warns before red.', difficulty: 'beginner' },
            { qtype: 'oneliner', prompt: 'One line: why is a resistor added with each LED?', answer: 'To limit current and protect the LED from burning out.', explanation: 'Resistors control current.', difficulty: 'intermediate' },
            { qtype: 'logical', prompt: 'A traffic light is an example of which computing idea?', options: ['State machine/sequence', 'Random noise', 'A single switch', 'A battery'], answer: 'State machine/sequence', explanation: 'It moves through ordered states.', difficulty: 'advanced' },
            { qtype: 'computational', prompt: 'If each light stays on 20s, how long is one full Red→Green→Yellow cycle?', options: ['20s', '40s', '60s', '80s'], answer: '60s', explanation: '3 × 20 = 60 seconds.', difficulty: 'beginner' },
            { qtype: 'brain_teaser', prompt: 'How could you make the signal stay green longer when more cars are waiting?', answer: 'Add a sensor that counts cars and adjusts the green time.', explanation: 'Inputs can change the timing logic.', difficulty: 'advanced' },
            { qtype: 'tinkering', prompt: 'Plan a 4-way intersection signal. How do you stop opposite-direction crashes?', answer: 'Open-ended', explanation: 'Only non-conflicting directions get green together.', difficulty: 'advanced' },
          ],
        },
      ],
    },
    {
      title: 'Mechanics',
      slug: 'mechanics',
      icon: '🦾',
      color: '#7209b7',
      description: 'Build machines that move, grab and lift using simple mechanisms.',
      chapters: [
        {
          title: 'DIY Grabber',
          difficulty: 'beginner', est: 60,
          summary: 'Build a reach-and-grab tool using levers and linkages from cardboard.',
          hook: 'Can you pick up an object from across the room without moving? Engineers built robotic arms from this very idea — a grabber!',
          layman: 'A grabber extends your reach. It uses a "linkage" — strips joined at pivots — that expands and squeezes when you press a handle. Push here, grab there!',
          concept: 'A linkage transfers motion and force from one place to another. A scissor/lazy-tong mechanism turns a small squeeze into a large reach.',
          howItWorks: [
            'Cardboard strips are pinned at crossing points to form X shapes.',
            'When you squeeze the handle, all X joints fold, extending the arm.',
            'Jaws at the far end close to grip an object.',
            'Release the handle and the jaws open via a rubber band.',
          ],
          realWorld: [
            'Litter-picking "reacher" tools for cleaning.',
            'Robotic arms on assembly lines.',
            'Surgical grabbers used in keyhole surgery.',
          ],
          logic: 'A linkage is a mechanical "function": input motion → output motion. Understanding how one movement maps to another is the same mapping logic used in programming functions.',
          steps: [
            'Cut equal cardboard strips and punch holes at the ends and centre.',
            'Pin strips into a row of X (lazy-tong) shapes.',
            'Attach simple jaws at the front.',
            'Add a rubber band so jaws spring open.',
            'Test grabbing light objects.',
          ],
          diagram: 'gear',
          facts: [
            'Lazy-tong mechanisms are used in expanding gates and old camera flashes.',
            'A linkage can change both the direction and amount of motion.',
            'The human hand has 27 bones — engineers copy it to build robotic grippers.',
          ],
          questions: [
            { qtype: 'mcq', prompt: 'A grabber mainly uses which mechanism?', options: ['Linkage', 'Battery', 'Sensor', 'Gear motor'], answer: 'Linkage', explanation: 'Crossed strips form a linkage.', difficulty: 'beginner' },
            { qtype: 'oneliner', prompt: 'One line: what makes the jaws spring open?', answer: 'A rubber band pulls them back open.', explanation: 'Stored elastic energy.', difficulty: 'beginner' },
            { qtype: 'logical', prompt: 'Squeezing a small distance makes the tip move a large distance. This is a trade of?', options: ['Force for distance', 'Color for sound', 'Nothing', 'Heat for light'], answer: 'Force for distance', explanation: 'Mechanisms trade force and distance.', difficulty: 'advanced' },
            { qtype: 'brain_teaser', prompt: 'Your grabber drops heavy items. Without a motor, how can you increase grip strength?', answer: 'Add grippy material, shorten the lever, or add a stronger spring.', explanation: 'Friction and leverage matter.', difficulty: 'advanced' },
            { qtype: 'tinkering', prompt: 'Modify your grabber to pick up a round ball that keeps slipping. What changes?', answer: 'Open-ended', explanation: 'Curved/grippy jaws hold round objects.', difficulty: 'advanced' },
          ],
        },
        {
          title: 'Robotic Arm',
          difficulty: 'intermediate', est: 60,
          summary: 'Construct a multi-joint robotic arm controlled by syringes or strings.',
          hook: 'Robots on factory floors weld cars and even perform surgery. Build your own arm with joints that bend on command!',
          layman: 'A robotic arm copies your arm: shoulder, elbow, wrist. Each joint bends separately. Using strings or water-filled syringes (hydraulics), you control each joint to reach and grab.',
          concept: 'An arm is a chain of joints (degrees of freedom). More joints = more positions it can reach. Controlling each joint independently lets the tip reach any point in its workspace.',
          howItWorks: [
            'Cardboard segments are connected with pivoting joints.',
            'Hydraulics: pushing one syringe pushes water that moves another, bending a joint.',
            'Each joint adds a "degree of freedom" (a way to move).',
            'Combining joints lets the gripper reach 3D positions.',
          ],
          realWorld: [
            'Car factory welding/painting robots.',
            'Mars rover sampling arms.',
            'Pick-and-place machines in warehouses.',
          ],
          logic: 'Reaching a target with multiple joints is a sequencing and coordination problem — like giving an algorithm precise ordered instructions to reach a goal.',
          steps: [
            'Cut arm segments and make hinged joints.',
            'Fix syringe pairs across each joint and fill with water.',
            'Push/pull syringes to test each joint.',
            'Add a gripper at the end.',
            'Practice picking and placing a small object.',
          ],
          diagram: 'gear',
          facts: [
            'Hydraulics use liquid pressure — the same idea powers JCB excavators.',
            'Industrial robot arms can repeat a move to within 0.01 mm.',
            '“Degrees of freedom” describe how many ways a robot can move.',
          ],
          questions: [
            { qtype: 'mcq', prompt: 'Each independent joint of a robotic arm adds a?', options: ['Color', 'Degree of freedom', 'Battery', 'Sensor'], answer: 'Degree of freedom', explanation: 'More joints → more reachable positions.', difficulty: 'intermediate' },
            { qtype: 'mcq', prompt: 'Water-filled syringes move joints using?', options: ['Electricity', 'Hydraulics (liquid pressure)', 'Magnets', 'Light'], answer: 'Hydraulics (liquid pressure)', explanation: 'Liquid transfers force.', difficulty: 'beginner' },
            { qtype: 'oneliner', prompt: 'One line: why use water instead of air in the syringes?', answer: 'Water barely compresses, so motion is precise.', explanation: 'Liquids transmit force directly.', difficulty: 'advanced' },
            { qtype: 'logical', prompt: 'An arm with more joints can reach?', options: ['Fewer positions', 'More positions', 'The same', 'No positions'], answer: 'More positions', explanation: 'More degrees of freedom.', difficulty: 'beginner' },
            { qtype: 'brain_teaser', prompt: 'Your arm sags under weight at full stretch. Give two engineering fixes.', answer: 'Lighter materials and stronger/closer joints or counterweights.', explanation: 'Reduce load or increase support.', difficulty: 'advanced' },
            { qtype: 'tinkering', prompt: 'Design a control panel so two people each control different joints to cooperate. How?', answer: 'Open-ended', explanation: 'Split controls per joint.', difficulty: 'advanced' },
          ],
        },
      ],
    },
    {
      title: '3D Design & Printing',
      slug: '3d-design-printing',
      icon: '🧊',
      color: '#4361ee',
      description: 'Turn ideas into real objects using 3D modelling and printing.',
      chapters: [
        {
          title: 'Design and Print a 3D Keychain',
          difficulty: 'beginner', est: 60,
          summary: 'Model your name keychain in TinkerCAD and prepare it for 3D printing.',
          hook: 'Imagine designing something on a screen and holding it in your hand an hour later. That is the magic of 3D printing!',
          layman: '3D design means building an object on the computer using simple shapes — boxes, cylinders, text. A 3D printer then builds it for real by stacking very thin layers of melted plastic.',
          concept: 'A 3D model has three dimensions: length, breadth and height. 3D printing is "additive manufacturing" — adding material layer by layer until the object is complete.',
          howItWorks: [
            'Combine basic shapes (text + a ring) in software like TinkerCAD.',
            'Export the design as an STL file.',
            'Slicing software cuts the model into thin layers and makes printer instructions.',
            'The printer melts plastic filament and lays it layer by layer.',
          ],
          realWorld: [
            'Custom name tags and keychains.',
            'Prosthetic hands printed cheaply for those in need.',
            'Spare parts printed on the International Space Station.',
          ],
          logic: 'Building complex objects from simple shapes is "decomposition" — breaking a big problem into small parts. It is the #1 skill in both design and programming.',
          steps: [
            'Open TinkerCAD and add a text shape with your name.',
            'Add a ring/hole for the key.',
            'Resize so it fits a keyring.',
            'Group the shapes into one object.',
            'Export as STL for printing.',
          ],
          diagram: 'cube3d',
          facts: [
            '3D printing is also called additive manufacturing.',
            'Most school printers use PLA plastic made from corn starch.',
            'The first 3D printer was invented in 1983 by Chuck Hull.',
          ],
          questions: [
            { qtype: 'mcq', prompt: '3D printing builds objects by?', options: ['Carving from a block', 'Adding material layer by layer', 'Melting metal only', 'Drawing on paper'], answer: 'Adding material layer by layer', explanation: 'Additive manufacturing.', difficulty: 'beginner' },
            { qtype: 'mcq', prompt: 'Which file format is commonly exported for printing?', options: ['MP3', 'STL', 'DOCX', 'JPG'], answer: 'STL', explanation: 'STL stores the 3D surface.', difficulty: 'intermediate' },
            { qtype: 'oneliner', prompt: 'One line: what are the three dimensions of a 3D object?', answer: 'Length, breadth and height.', explanation: 'Three axes.', difficulty: 'beginner' },
            { qtype: 'logical', prompt: 'Making a keychain from a text shape + a ring shape is an example of?', options: ['Decomposition', 'Randomness', 'Soldering', 'Painting'], answer: 'Decomposition', explanation: 'Build from simple parts.', difficulty: 'advanced' },
            { qtype: 'computational', prompt: 'If each printed layer is 0.2 mm, how many layers make a 10 mm tall keychain?', options: ['5', '50', '500', '20'], answer: '50', explanation: '10 ÷ 0.2 = 50 layers.', difficulty: 'intermediate' },
            { qtype: 'brain_teaser', prompt: 'Your printed letters keep breaking off. Without changing the printer, how do you make them stronger?', answer: 'Make letters thicker/connected and add a base bar.', explanation: 'Thin parts are weak.', difficulty: 'advanced' },
            { qtype: 'tinkering', prompt: 'Design a keychain that also works as a bottle opener. Sketch the shape.', answer: 'Open-ended', explanation: 'Combine functions in one object.', difficulty: 'advanced' },
          ],
        },
        {
          title: 'Design and 3D Print a Cup',
          difficulty: 'intermediate', est: 60,
          summary: 'Model a hollow cup and learn about walls, holes and watertight designs.',
          hook: 'A cup looks simple — but how do you make a 3D model hollow so it can actually hold water?',
          layman: 'A cup is a cylinder with the inside scooped out. In 3D software you place a smaller cylinder inside a bigger one and turn it into a "hole" to hollow it out.',
          concept: 'Hollow objects use a "shell": an outer wall with empty space inside. Wall thickness must be strong enough to hold shape and (for a cup) watertight.',
          howItWorks: [
            'Create a solid cylinder for the outer body.',
            'Place a smaller cylinder inside and set it as a hole.',
            'Group them — the inner cylinder carves out the hollow.',
            'Keep the base solid so liquid does not leak.',
          ],
          realWorld: [
            'Designing bottles, vases and containers.',
            'Engineering hollow parts to save material and weight.',
            'Custom measuring cups for science labs.',
          ],
          logic: 'Choosing wall thickness is an optimization: too thin = leaks/breaks, too thick = wastes plastic and time. Balancing constraints is core engineering and computational thinking.',
          steps: [
            'Add a cylinder as the cup body.',
            'Add a smaller cylinder, raise it slightly, set as hole.',
            'Leave a solid base.',
            'Group to hollow it out.',
            'Export and (optionally) print.',
          ],
          diagram: 'cube3d',
          facts: [
            'Wall thickness under 1 mm often fails to print cleanly.',
            'Hollow designs save filament and print faster.',
            'Watertight prints may need extra wall layers to avoid leaks.',
          ],
          questions: [
            { qtype: 'mcq', prompt: 'To hollow a cup in 3D software you use a?', options: ['Solid only', 'Hole/negative shape', 'Bigger solid', 'A photo'], answer: 'Hole/negative shape', explanation: 'A hole subtracts material.', difficulty: 'beginner' },
            { qtype: 'oneliner', prompt: 'One line: why must the cup base stay solid?', answer: 'So the liquid does not leak out of the bottom.', explanation: 'Open base = leak.', difficulty: 'beginner' },
            { qtype: 'computational', prompt: 'Outer radius 30 mm, inner radius 27 mm. What is the wall thickness?', options: ['57 mm', '3 mm', '30 mm', '27 mm'], answer: '3 mm', explanation: '30 − 27 = 3 mm.', difficulty: 'intermediate' },
            { qtype: 'logical', prompt: 'Walls too thin cause leaks; too thick wastes plastic. Choosing the right value is?', options: ['Optimization', 'Guessing', 'Painting', 'Soldering'], answer: 'Optimization', explanation: 'Balance constraints.', difficulty: 'advanced' },
            { qtype: 'brain_teaser', prompt: 'How would you design a cup that cannot be put down until empty (a “puzzle cup”)?', answer: 'Round/pointed base so it tips unless held — like a Greek pythagorean cup idea.', explanation: 'Shape controls stability.', difficulty: 'advanced' },
            { qtype: 'tinkering', prompt: 'Design a travel cup with a lid that snaps on. Describe the fit.', answer: 'Open-ended', explanation: 'Lip and groove create a snap fit.', difficulty: 'advanced' },
          ],
        },
      ],
    },
    {
      title: 'Data Visualization',
      slug: 'data-visualization',
      icon: '📊',
      color: '#06d6a0',
      description: 'Turn everyday data into charts that tell powerful stories.',
      chapters: [
        {
          title: 'How Do I Spend My Day?',
          difficulty: 'beginner', est: 60,
          summary: 'Track your daily activities and turn them into a pie/bar chart to find insights.',
          hook: 'Where does your time actually go each day? Numbers hide the truth — but a chart reveals it instantly!',
          layman: 'Data is just information — like how many hours you sleep, study or play. On its own it is boring numbers. A chart turns those numbers into a picture your eyes understand in a second.',
          concept: 'Data visualization converts numbers into visual shapes (bars, slices, lines) so patterns and comparisons become obvious. The right chart matches the kind of question you ask.',
          howItWorks: [
            'Collect data: list activities and hours for one day (must total 24).',
            'Organize it in a table.',
            'Pick a chart: pie for parts of a whole, bar for comparisons.',
            'Read the chart to spot the biggest/smallest slices.',
          ],
          realWorld: [
            'Cricket scoreboards and run-rate graphs.',
            'Weather temperature line charts.',
            'Screen-time reports on your phone.',
          ],
          logic: 'Collecting, organizing and representing data is the foundation of data science and AI. Spotting patterns in a chart is "pattern recognition" — exactly what machine learning automates.',
          steps: [
            'Write down each activity and hours for today.',
            'Check the total adds to 24 hours.',
            'Draw a pie chart by splitting a circle by proportion.',
            'Mark the largest and smallest slice.',
            'Write one insight you discovered.',
          ],
          diagram: 'chart',
          facts: [
            'The pie chart was popularised by nurse Florence Nightingale to save lives.',
            'A good chart can replace a whole page of numbers.',
            '“A picture is worth a thousand words” — and a thousand data points!',
          ],
          questions: [
            { qtype: 'mcq', prompt: 'Which chart best shows parts of a whole (a single day)?', options: ['Line chart', 'Pie chart', 'No chart', 'Map'], answer: 'Pie chart', explanation: 'Pie shows proportions.', difficulty: 'beginner' },
            { qtype: 'oneliner', prompt: 'One line: why do we visualize data?', answer: 'To understand patterns quickly that raw numbers hide.', explanation: 'Visuals are fast to read.', difficulty: 'beginner' },
            { qtype: 'computational', prompt: 'You sleep 8 of 24 hours. What fraction (and rough %) of the pie is sleep?', options: ['1/3 (~33%)', '1/2 (50%)', '1/4 (25%)', '1/8'], answer: '1/3 (~33%)', explanation: '8/24 = 1/3 ≈ 33%.', difficulty: 'intermediate' },
            { qtype: 'logical', prompt: 'Spotting that you study only 1 hour is an example of?', options: ['Pattern recognition', 'Soldering', 'Random guess', 'Printing'], answer: 'Pattern recognition', explanation: 'Insight from data.', difficulty: 'advanced' },
            { qtype: 'brain_teaser', prompt: 'Your day totals 26 hours in your table. What does this tell you and how do you fix it?', answer: 'There is a data error; recheck and correct entries to total 24.', explanation: 'Validate data before trusting it.', difficulty: 'advanced' },
            { qtype: 'tinkering', prompt: 'Design a weekly time tracker and decide which chart shows improvement over days.', answer: 'Open-ended', explanation: 'Line/bar charts show trends.', difficulty: 'advanced' },
          ],
        },
      ],
    },
    {
      title: 'Design & Entrepreneurial Thinking',
      slug: 'design-thinking',
      icon: '💡',
      color: '#ffd166',
      description: 'Solve real problems creatively using the design thinking process.',
      chapters: [
        {
          title: 'Design Thinking and Prototyping',
          difficulty: 'intermediate', est: 60,
          summary: 'Learn the 5-step design thinking process and build a quick prototype to solve a real problem.',
          hook: 'The best inventions did not start perfect — they started as rough cardboard models. How do innovators turn problems into products?',
          layman: 'Design thinking is a recipe for solving problems by first deeply understanding people’s needs, then imagining many ideas, building a rough model (prototype), and testing it. Fail fast, learn fast, improve.',
          concept: 'Design thinking has 5 stages: Empathize → Define → Ideate → Prototype → Test. It is human-centred: solutions must fit real people’s needs, not just look cool.',
          howItWorks: [
            'Empathize: observe and talk to users to understand their real problem.',
            'Define: write a clear problem statement.',
            'Ideate: brainstorm many solutions without judging.',
            'Prototype: build a quick, cheap model.',
            'Test: get feedback and improve — repeat the loop.',
          ],
          realWorld: [
            'Redesigning an auto-rickshaw to be safer.',
            'Apps redesigned after watching users get confused.',
            'Affordable products built for rural needs.',
          ],
          logic: 'The build–test–improve loop is "iteration" — the same loop used in coding (write, run, fix). Iteration beats trying to be perfect on the first attempt.',
          steps: [
            'Pick a small everyday problem around you.',
            'Interview 2 people who face it (Empathize).',
            'Write a one-line problem statement (Define).',
            'Brainstorm 10 ideas in 5 minutes (Ideate).',
            'Build a cardboard/paper prototype and test it.',
          ],
          diagram: 'design_thinking',
          facts: [
            'Design thinking was popularised by the design firm IDEO and Stanford d.school.',
            'A prototype can be as simple as a paper sketch.',
            'Entrepreneurs test ideas cheaply before spending big money.',
          ],
          questions: [
            { qtype: 'mcq', prompt: 'What is the FIRST stage of design thinking?', options: ['Test', 'Empathize', 'Prototype', 'Sell'], answer: 'Empathize', explanation: 'Understand users first.', difficulty: 'beginner' },
            { qtype: 'mcq', prompt: 'A prototype is best described as a?', options: ['Final product', 'Quick, rough model to test ideas', 'Sales receipt', 'Advertisement'], answer: 'Quick, rough model to test ideas', explanation: 'Cheap and fast to learn.', difficulty: 'beginner' },
            { qtype: 'oneliner', prompt: 'One line: why prototype before building the final product?', answer: 'To learn and fix problems cheaply before spending big.', explanation: 'Fail fast, learn fast.', difficulty: 'intermediate' },
            { qtype: 'logical', prompt: 'Build → Test → Improve → repeat is called?', options: ['Iteration', 'Deletion', 'Soldering', 'Sleeping'], answer: 'Iteration', explanation: 'Looping to improve.', difficulty: 'advanced' },
            { qtype: 'brain_teaser', prompt: 'Two great ideas, little money and time. How do you decide which to build first?', answer: 'Prototype the cheaper/faster one and test with users to get data.', explanation: 'Let evidence decide.', difficulty: 'advanced' },
            { qtype: 'tinkering', prompt: 'Use design thinking to redesign your school bag for back pain. Outline all 5 stages.', answer: 'Open-ended', explanation: 'Apply the full process.', difficulty: 'advanced' },
          ],
        },
      ],
    },
  ],
};
