import { GradeSpec } from './curriculum';

export const grade7: GradeSpec = {
  number: 7,
  name: 'Class 7',
  level_label: 'ATL Tinkering Level II',
  description: 'Level up: sensors, solar energy, Arduino programming, hydraulics and rocket design.',
  modules: [
    {
      title: 'Basic Electronics',
      slug: 'basic-electronics',
      icon: '⚡',
      color: '#f72585',
      description: 'Sensors, solar power and the Arduino — your first programmable brain.',
      chapters: [
        {
          title: 'Automatic Street Light using LDR',
          difficulty: 'intermediate', est: 60,
          summary: 'Build a light that switches ON automatically in the dark using an LDR sensor and a transistor.',
          hook: 'Street lights glow at night and switch off at dawn — with no human pressing a switch. What is their hidden “eye”?',
          layman: 'An LDR (Light Dependent Resistor) is an electronic “eye”. In bright light it lets current pass easily; in darkness it blocks current. A transistor uses this to switch a bulb ON when it gets dark.',
          concept: 'A sensor converts a real-world signal (light) into an electrical signal. An LDR changes its resistance with light. A transistor acts as a switch controlled by this small signal.',
          howItWorks: [
            'In daylight the LDR has low resistance → the control circuit keeps the light OFF.',
            'In darkness the LDR resistance rises → voltage at the transistor base rises.',
            'The transistor turns ON like a switch and powers the LED/bulb.',
            'At dawn the cycle reverses automatically.',
          ],
          realWorld: [
            'Automatic street lights and garden lights.',
            'Phone screens that dim in the dark (ambient light sensor).',
            'Automatic night lamps in homes.',
          ],
          logic: 'This is an “if-then” rule in hardware: IF dark THEN light ON. Recognising condition→action logic is the heart of programming and automation.',
          steps: [
            'Build a voltage divider with the LDR and a fixed resistor.',
            'Feed the middle point to a transistor base.',
            'Connect an LED to the transistor output.',
            'Cover the LDR to simulate darkness and watch the LED turn on.',
          ],
          code: { language: 'text', code: 'IF light_level < threshold THEN turn_LED_ON\nELSE turn_LED_OFF', note: 'The hardware behaves exactly like this rule.' },
          diagram: 'sensor',
          facts: [
            'LDRs are made of cadmium sulphide, which reacts to light.',
            'A transistor can switch millions of times per second.',
            'Automatic lighting saves huge amounts of electricity worldwide.',
          ],
          questions: [
            { qtype: 'mcq', prompt: 'An LDR changes its ____ depending on light.', options: ['Color', 'Resistance', 'Weight', 'Sound'], answer: 'Resistance', explanation: 'LDR = Light Dependent Resistor.', difficulty: 'beginner' },
            { qtype: 'mcq', prompt: 'In the dark, the street light turns?', options: ['OFF', 'ON', 'Explodes', 'Nothing'], answer: 'ON', explanation: 'High LDR resistance triggers the switch.', difficulty: 'beginner' },
            { qtype: 'oneliner', prompt: 'One line: what job does the transistor do here?', answer: 'It acts as an electronic switch controlled by the LDR.', explanation: 'Small signal controls big load.', difficulty: 'intermediate' },
            { qtype: 'logical', prompt: '“IF dark THEN light ON” is an example of?', options: ['Conditional logic', 'Random noise', 'A battery', 'A gear'], answer: 'Conditional logic', explanation: 'Condition → action.', difficulty: 'advanced' },
            { qtype: 'computational', prompt: 'If the LDR is 1kΩ in light and 100kΩ in dark, when is resistance higher?', options: ['In light', 'In dark', 'Always equal', 'Never'], answer: 'In dark', explanation: '100kΩ > 1kΩ.', difficulty: 'beginner' },
            { qtype: 'brain_teaser', prompt: 'Car headlights at night could fool your street light to turn off. How do you prevent false triggering?', answer: 'Add a delay/averaging so brief light flashes are ignored.', explanation: 'Filter noisy inputs.', difficulty: 'advanced' },
            { qtype: 'tinkering', prompt: 'Design a lamp that gets brighter as the room gets darker (not just on/off). How?', answer: 'Open-ended', explanation: 'Map LDR value to LED brightness (PWM).', difficulty: 'advanced' },
          ],
        },
        {
          title: 'Solar Powered Electric Fan',
          difficulty: 'intermediate', est: 60,
          summary: 'Convert sunlight into motion by powering a small DC fan with a solar panel.',
          hook: 'Could the Sun spin a fan with zero electricity bill and zero pollution? Yes — with a solar cell!',
          layman: 'A solar panel turns sunlight directly into electricity. Connect it to a small motor with fan blades and the fan spins whenever the Sun shines — clean, free energy.',
          concept: 'Solar cells use the photovoltaic effect: light particles (photons) knock electrons loose in silicon, creating a flow of electricity. More light or larger panel = more power.',
          howItWorks: [
            'Sunlight hits the solar panel and frees electrons in the silicon.',
            'This creates a DC voltage across the panel terminals.',
            'The voltage drives current through the DC motor.',
            'The motor spins the fan; brighter light = faster spin.',
          ],
          realWorld: [
            'Solar rooftop systems powering homes.',
            'Solar-powered calculators and garden lights.',
            'Solar water pumps for farms.',
          ],
          logic: 'Energy is converted, not created: light → electrical → mechanical. Tracing energy through a system is systems thinking — seeing inputs, transformations and outputs.',
          steps: [
            'Connect the solar panel to a small DC motor.',
            'Attach lightweight fan blades to the motor shaft.',
            'Take it into sunlight and observe the spin.',
            'Shade the panel partly and note the slowdown.',
          ],
          diagram: 'flow',
          facts: [
            'The Sun delivers more energy to Earth in 1 hour than humans use in a year.',
            'Solar panels still work (less) on cloudy days using diffuse light.',
            'India is among the world’s largest solar energy producers.',
          ],
          questions: [
            { qtype: 'mcq', prompt: 'A solar panel converts sunlight into?', options: ['Sound', 'Electricity', 'Water', 'Heat only'], answer: 'Electricity', explanation: 'Photovoltaic effect.', difficulty: 'beginner' },
            { qtype: 'mcq', prompt: 'The energy chain here is light → electrical → ?', options: ['Sound', 'Mechanical (motion)', 'Chemical', 'Nuclear'], answer: 'Mechanical (motion)', explanation: 'Motor spins the fan.', difficulty: 'intermediate' },
            { qtype: 'oneliner', prompt: 'One line: what happens to fan speed when light increases?', answer: 'The fan spins faster with more light.', explanation: 'More power.', difficulty: 'beginner' },
            { qtype: 'logical', prompt: 'Tracing light→electricity→motion is an example of?', options: ['Systems thinking', 'Soldering', 'Random guess', 'Painting'], answer: 'Systems thinking', explanation: 'Input→transform→output.', difficulty: 'advanced' },
            { qtype: 'brain_teaser', prompt: 'Your solar fan stops when a cloud passes. How can you keep it running briefly without the Sun?', answer: 'Add a rechargeable battery/capacitor that stores energy.', explanation: 'Energy storage buffers supply.', difficulty: 'advanced' },
            { qtype: 'tinkering', prompt: 'Design a solar gadget that always faces the Sun for maximum power. How would it track?', answer: 'Open-ended', explanation: 'Light sensors + motor = solar tracker.', difficulty: 'advanced' },
          ],
        },
        {
          title: 'Basics of Arduino - 1',
          difficulty: 'intermediate', est: 60,
          summary: 'Meet the Arduino board and write your first program to blink an LED.',
          hook: 'What if you could give a tiny computer your own instructions and it obeyed instantly? Welcome to Arduino!',
          layman: 'An Arduino is a small programmable brain. You write simple instructions on a computer, upload them, and the board controls lights, motors and sensors. The classic first program makes an LED blink.',
          concept: 'A microcontroller runs your code in a loop. Pins can be OUTPUTS (control things) or INPUTS (read things). setup() runs once; loop() runs forever.',
          howItWorks: [
            'You write code in the Arduino IDE in two parts: setup() and loop().',
            'setup() configures pins (e.g., LED pin as OUTPUT).',
            'loop() repeats forever: turn LED on, wait, turn off, wait.',
            'Upload sends the program to the board, which runs independently.',
          ],
          realWorld: [
            '3D printers and CNC machines use microcontrollers.',
            'Smart home gadgets and robots.',
            'Science fair projects and wearables.',
          ],
          logic: 'setup() once + loop() forever teaches program structure and the concept of a loop — the most powerful idea in programming: repeat instructions automatically.',
          steps: [
            'Connect the Arduino to the computer via USB.',
            'Open the Arduino IDE and select the board/port.',
            'Write the Blink sketch (below).',
            'Upload and watch the on-board LED blink.',
            'Change the delay to blink faster/slower.',
          ],
          code: {
            language: 'cpp',
            code: 'void setup() {\n  pinMode(13, OUTPUT);   // LED pin\n}\n\nvoid loop() {\n  digitalWrite(13, HIGH); // LED on\n  delay(1000);            // wait 1 second\n  digitalWrite(13, LOW);  // LED off\n  delay(1000);            // wait 1 second\n}',
            note: 'This is the famous “Blink” — the Hello World of hardware.',
          },
          diagram: 'arduino',
          facts: [
            'Arduino was born in Italy in 2005 to help design students.',
            'delay(1000) means wait 1000 milliseconds = 1 second.',
            'Millions of makers worldwide start with the Blink sketch.',
          ],
          questions: [
            { qtype: 'mcq', prompt: 'Which Arduino function runs only once at start?', options: ['loop()', 'setup()', 'blink()', 'main()'], answer: 'setup()', explanation: 'setup runs once.', difficulty: 'beginner' },
            { qtype: 'mcq', prompt: 'delay(1000) waits for how long?', options: ['1000 seconds', '1 second', '1 minute', '10 seconds'], answer: '1 second', explanation: '1000 ms = 1 s.', difficulty: 'beginner' },
            { qtype: 'oneliner', prompt: 'One line: what does loop() do?', answer: 'It repeats its instructions forever.', explanation: 'Infinite loop.', difficulty: 'beginner' },
            { qtype: 'computational', prompt: 'With on=1s and off=1s, how many full blinks happen in 10 seconds?', options: ['10', '5', '20', '2'], answer: '5', explanation: 'Each blink takes 2s → 10/2 = 5.', difficulty: 'intermediate' },
            { qtype: 'logical', prompt: 'To make the LED blink twice as fast you should?', options: ['Increase delay', 'Decrease delay', 'Remove setup', 'Unplug it'], answer: 'Decrease delay', explanation: 'Shorter waits → faster blink.', difficulty: 'intermediate' },
            { qtype: 'brain_teaser', prompt: 'Without delay(), how else could you blink an LED while also reading a button at the same time?', answer: 'Use millis() timing so the code never fully pauses.', explanation: 'Non-blocking timing.', difficulty: 'advanced' },
            { qtype: 'tinkering', prompt: 'Write the idea (pseudocode) for an SOS Morse blinker: 3 short, 3 long, 3 short.', answer: 'Open-ended', explanation: 'Sequence of timed on/off.', difficulty: 'advanced' },
          ],
        },
        {
          title: 'Basics of Arduino - 2',
          difficulty: 'advanced', est: 60,
          summary: 'Read inputs: control an LED with a push button and react to the real world.',
          hook: 'A blinking light is cool — but a machine that reacts to YOU is magic. Let’s make Arduino listen!',
          layman: 'Now the Arduino reads an input — a push button. When you press it, the program decides what to do (e.g., turn on an LED). This is the difference between a toy and a smart device: it senses and reacts.',
          concept: 'Inputs are read with digitalRead(). An if-statement makes decisions based on the input. This input→decision→output pattern is the basis of all interactive systems.',
          howItWorks: [
            'A button pin is set as INPUT (often INPUT_PULLUP).',
            'digitalRead() checks if the button is pressed (HIGH/LOW).',
            'An if-statement decides the action.',
            'digitalWrite() turns the LED on or off accordingly.',
          ],
          realWorld: [
            'Doorbells and elevator buttons.',
            'Game controllers.',
            'Emergency stop buttons on machines.',
          ],
          logic: 'IF (button pressed) THEN (do action) is conditional branching — the decision-making core of every program and AI rule system.',
          steps: [
            'Wire a push button to a digital input pin.',
            'Set the LED pin as OUTPUT and button pin as INPUT.',
            'Read the button each loop.',
            'Use if/else to control the LED.',
            'Test pressing and releasing.',
          ],
          code: {
            language: 'cpp',
            code: 'int button = 2, led = 13;\nvoid setup(){\n  pinMode(led, OUTPUT);\n  pinMode(button, INPUT_PULLUP);\n}\nvoid loop(){\n  if (digitalRead(button) == LOW) // pressed\n    digitalWrite(led, HIGH);\n  else\n    digitalWrite(led, LOW);\n}',
            note: 'INPUT_PULLUP makes an unpressed button read HIGH and a pressed one LOW.',
          },
          diagram: 'arduino',
          facts: [
            'A “pull-up resistor” keeps an input from floating between 0 and 1.',
            'Buttons can “bounce” — sending several signals from one press.',
            'digitalRead returns either HIGH (1) or LOW (0).',
          ],
          questions: [
            { qtype: 'mcq', prompt: 'Which function reads a button state?', options: ['digitalWrite()', 'digitalRead()', 'delay()', 'pinMode()'], answer: 'digitalRead()', explanation: 'Read = input.', difficulty: 'beginner' },
            { qtype: 'mcq', prompt: 'Making a decision in code uses a(n)?', options: ['if-statement', 'delay', 'comment', 'wire'], answer: 'if-statement', explanation: 'Conditional branching.', difficulty: 'beginner' },
            { qtype: 'oneliner', prompt: 'One line: what does input→decision→output describe?', answer: 'How an interactive/smart device works.', explanation: 'Sense, decide, act.', difficulty: 'intermediate' },
            { qtype: 'logical', prompt: 'With INPUT_PULLUP, an unpressed button reads?', options: ['HIGH', 'LOW', 'Random', 'Nothing'], answer: 'HIGH', explanation: 'Pull-up holds it HIGH.', difficulty: 'advanced' },
            { qtype: 'brain_teaser', prompt: 'One press sometimes turns the LED on AND off rapidly. What causes it and one fix?', answer: 'Button bounce; fix with a small delay or debounce logic.', explanation: 'Mechanical contacts chatter.', difficulty: 'advanced' },
            { qtype: 'tinkering', prompt: 'Design a 2-button game: one scores, one resets. Describe the logic.', answer: 'Open-ended', explanation: 'Track a score variable with conditions.', difficulty: 'advanced' },
          ],
        },
      ],
    },
    {
      title: 'Mechanics',
      slug: 'mechanics',
      icon: '🦾',
      color: '#7209b7',
      description: 'Hydraulics and walking robots — make machines move with force.',
      chapters: [
        {
          title: 'Hydraulic Lift',
          difficulty: 'intermediate', est: 60,
          summary: 'Lift heavy loads with little effort using water-filled syringes (Pascal’s law).',
          hook: 'How can a small push lift a heavy car? The answer flows through hydraulic pipes!',
          layman: 'Hydraulics use trapped liquid to transfer force. Push a small syringe and the pressure travels through the tube to a bigger syringe, pushing it up with greater force — that is how a lift works.',
          concept: 'Pascal’s Law: pressure applied to a confined liquid is transmitted equally in all directions. A larger output piston multiplies force (but moves a shorter distance).',
          howItWorks: [
            'Two syringes are joined by a water-filled tube.',
            'Pushing the small (input) syringe raises the liquid pressure.',
            'Pressure pushes the larger (output) syringe up.',
            'Bigger output area → more lifting force.',
          ],
          realWorld: [
            'Car service-station lifts and JCB excavators.',
            'Hydraulic brakes in vehicles.',
            'Dentist and barber chairs.',
          ],
          logic: 'Force multiplication is a trade-off: you gain force but lose distance (energy is conserved). Recognising conservation laws helps you predict system behaviour.',
          steps: [
            'Fill two syringes and tube with water (no air bubbles).',
            'Connect them and build a lifting platform on the output syringe.',
            'Push the input syringe to raise a load.',
            'Try different syringe sizes and compare lift force.',
          ],
          diagram: 'gear',
          facts: [
            'Pascal’s law was discovered by Blaise Pascal in the 1600s.',
            'Air bubbles ruin hydraulics because air compresses.',
            'Hydraulic systems can lift many tonnes effortlessly.',
          ],
          questions: [
            { qtype: 'mcq', prompt: 'Hydraulics work because pressure in a liquid is transmitted?', options: ['Only upward', 'Equally in all directions', 'Nowhere', 'Only down'], answer: 'Equally in all directions', explanation: 'Pascal’s law.', difficulty: 'beginner' },
            { qtype: 'mcq', prompt: 'Why is air bad in a hydraulic system?', options: ['It is heavy', 'Air compresses and wastes force', 'It is colorful', 'It cools the water'], answer: 'Air compresses and wastes force', explanation: 'Liquids barely compress.', difficulty: 'intermediate' },
            { qtype: 'oneliner', prompt: 'One line: a bigger output piston gives more force but less?', answer: 'Less distance moved.', explanation: 'Energy is conserved.', difficulty: 'advanced' },
            { qtype: 'computational', prompt: 'Input area 1cm², output area 5cm². Force is multiplied roughly by?', options: ['1×', '5×', '0.2×', '25×'], answer: '5×', explanation: 'Force scales with area ratio.', difficulty: 'advanced' },
            { qtype: 'brain_teaser', prompt: 'You gain 5× force but the load barely rises. Why, and how do you raise it higher?', answer: 'Distance traded for force; use a larger input stroke or pump repeatedly.', explanation: 'Trade-off + pumping.', difficulty: 'advanced' },
            { qtype: 'tinkering', prompt: 'Design a hydraulic bridge that lifts to let boats pass. Sketch the syringes.', answer: 'Open-ended', explanation: 'Output syringes raise the deck.', difficulty: 'advanced' },
          ],
        },
        {
          title: 'BugBot',
          difficulty: 'intermediate', est: 60,
          summary: 'Build a tiny vibrating robot that scurries like an insect using a motor and battery.',
          hook: 'Can a toothbrush head become a racing robot? Add a buzzing motor and watch it dash!',
          layman: 'A BugBot is a simple robot that moves using vibration. A small motor with an off-centre weight shakes the body, and angled bristles turn those vibrations into forward scampering — no wheels needed!',
          concept: 'An unbalanced spinning weight creates vibration. Slanted legs/bristles convert random shaking into directed motion — a clever use of friction and geometry.',
          howItWorks: [
            'A motor spins an off-centre weight, shaking the body rapidly.',
            'Angled bristles grip and release the floor as it vibrates.',
            'This ratchet-like action pushes the bot forward.',
            'Battery powers the motor continuously.',
          ],
          realWorld: [
            'Your phone’s vibrate mode uses the same off-centre motor.',
            'Vibration is used in concrete compactors and massagers.',
            'Swarm-robotics research uses simple vibrobots.',
          ],
          logic: 'Turning random vibration into directed motion shows how structure (slanted legs) shapes behaviour — small design choices produce big differences in outcome.',
          steps: [
            'Attach a vibration motor to a small body (e.g., brush head).',
            'Connect a coin cell to the motor.',
            'Angle the bristles all in one direction.',
            'Switch on and race your BugBot!',
          ],
          diagram: 'flow',
          facts: [
            'Phone vibration motors spin a tiny weight thousands of times a minute.',
            'Slanting the bristles controls the direction of travel.',
            'These robots are called “bristlebots”.',
          ],
          questions: [
            { qtype: 'mcq', prompt: 'A BugBot moves using?', options: ['Wheels', 'Vibration', 'Magnets', 'Water'], answer: 'Vibration', explanation: 'Off-centre weight shakes it.', difficulty: 'beginner' },
            { qtype: 'oneliner', prompt: 'One line: what makes the motor cause vibration?', answer: 'An off-centre (unbalanced) weight on the shaft.', explanation: 'Imbalance = shaking.', difficulty: 'intermediate' },
            { qtype: 'logical', prompt: 'Slanting all bristles one way mainly controls?', options: ['Color', 'Direction of motion', 'Battery life', 'Sound'], answer: 'Direction of motion', explanation: 'Geometry directs motion.', difficulty: 'advanced' },
            { qtype: 'brain_teaser', prompt: 'Your BugBot only spins in circles. What is likely wrong and how to fix it?', answer: 'Uneven legs/weight; balance the bristles and centre the motor.', explanation: 'Symmetry → straight motion.', difficulty: 'advanced' },
            { qtype: 'tinkering', prompt: 'Make a BugBot that can be steered left/right. What would you add?', answer: 'Open-ended', explanation: 'Two motors controlled separately.', difficulty: 'advanced' },
          ],
        },
      ],
    },
    {
      title: '3D Design & Printing',
      slug: '3d-design-printing',
      icon: '🧊',
      color: '#4361ee',
      description: 'Design functional objects: a rocket and a phone holder.',
      chapters: [
        {
          title: 'Design a Rocket and 3D Print It',
          difficulty: 'intermediate', est: 60,
          summary: 'Model an aerodynamic rocket and learn how shape affects flight.',
          hook: 'Why are rockets pointy with fins? Design one in 3D and discover the science of flight!',
          layman: 'A rocket’s shape is not just for looks. A pointed nose cuts through air, a tube body holds everything, and fins keep it flying straight. You will combine cones, cylinders and fins into one 3D model.',
          concept: 'Aerodynamics is about reducing air resistance (drag) and keeping stability. A streamlined nose, balanced body and rear fins make flight smooth and straight.',
          howItWorks: [
            'A cone forms the nose to reduce drag.',
            'A cylinder forms the body to carry payload.',
            'Fins at the back provide stability (like feathers on an arrow).',
            'Centre of mass forward of fins keeps it pointing ahead.',
          ],
          realWorld: [
            'Real space rockets like ISRO’s PSLV.',
            'Water rockets and model rocketry.',
            'Aerodynamic designs of cars and planes.',
          ],
          logic: 'Designing for a goal (straight, stable flight) under constraints (drag, balance) is engineering optimization — improving a design against measurable targets.',
          steps: [
            'Create a cylinder body in TinkerCAD.',
            'Add a cone nose on top.',
            'Add 3–4 fins around the base.',
            'Group into one model and export STL.',
            'Discuss how fin size changes stability.',
          ],
          diagram: 'cube3d',
          facts: [
            'Fins work like the feathers (fletching) on an arrow.',
            'Drag increases sharply as speed rises.',
            'India’s Mangalyaan reached Mars on its first attempt in 2014.',
          ],
          questions: [
            { qtype: 'mcq', prompt: 'Rocket fins mainly provide?', options: ['Color', 'Stability/straight flight', 'Weight', 'Sound'], answer: 'Stability/straight flight', explanation: 'Like arrow feathers.', difficulty: 'beginner' },
            { qtype: 'mcq', prompt: 'The pointed nose helps to?', options: ['Increase drag', 'Reduce air resistance (drag)', 'Add weight', 'Make noise'], answer: 'Reduce air resistance (drag)', explanation: 'Streamlining.', difficulty: 'beginner' },
            { qtype: 'oneliner', prompt: 'One line: which basic shapes build a rocket model?', answer: 'A cone (nose), a cylinder (body) and fins.', explanation: 'Decomposition.', difficulty: 'beginner' },
            { qtype: 'logical', prompt: 'Improving a design to fly straighter against drag is?', options: ['Optimization', 'Guessing', 'Painting', 'Random'], answer: 'Optimization', explanation: 'Goal under constraints.', difficulty: 'advanced' },
            { qtype: 'brain_teaser', prompt: 'Your rocket tumbles in flight. Name two design changes to stabilise it.', answer: 'Larger/rear fins and shift mass forward.', explanation: 'Move centre of mass ahead of centre of pressure.', difficulty: 'advanced' },
            { qtype: 'tinkering', prompt: 'Design a rocket nose that can carry and release a small parachute. How?', answer: 'Open-ended', explanation: 'Hollow nose + ejection.', difficulty: 'advanced' },
          ],
        },
        {
          title: 'Design a Simple Mobile Holder and 3D Print It',
          difficulty: 'beginner', est: 60,
          summary: 'Create a practical phone stand and learn about balance, angle and ergonomics.',
          hook: 'Tired of propping your phone against books? Design a perfect stand that holds it at just the right angle!',
          layman: 'A phone holder must balance the phone without tipping and hold it at a comfortable viewing angle. You will design a base, a back-rest and a small lip to stop the phone sliding.',
          concept: 'Stability comes from a wide base and low centre of gravity. Ergonomics means designing for comfortable human use — the right angle for the eyes and hands.',
          howItWorks: [
            'A flat base gives stability and stops tipping.',
            'A back support sets the viewing angle (~60°).',
            'A front lip stops the phone from sliding off.',
            'A cable slot lets you charge while docked.',
          ],
          realWorld: [
            'Desk phone and tablet stands.',
            'Laptop and book stands for better posture.',
            'Display stands in shops.',
          ],
          logic: 'Designing for the user (angle, grip, charging) is human-centred design — the same empathy-first thinking from design thinking, applied to a 3D object.',
          steps: [
            'Design a wide flat base.',
            'Add an angled back support.',
            'Add a small front lip.',
            'Cut a slot for the charging cable.',
            'Export STL and test-fit a phone (on screen).',
          ],
          diagram: 'cube3d',
          facts: [
            'A lower centre of gravity makes objects harder to tip.',
            'Around 60° is a comfortable screen-viewing angle.',
            'Good ergonomics reduces neck and eye strain.',
          ],
          questions: [
            { qtype: 'mcq', prompt: 'What makes the phone stand hard to tip over?', options: ['A tall thin base', 'A wide base, low centre of gravity', 'No base', 'Bright color'], answer: 'A wide base, low centre of gravity', explanation: 'Stability basics.', difficulty: 'beginner' },
            { qtype: 'oneliner', prompt: 'One line: what stops the phone sliding off the stand?', answer: 'A small front lip/ledge.', explanation: 'Physical stopper.', difficulty: 'beginner' },
            { qtype: 'logical', prompt: 'Designing the angle for comfortable viewing is?', options: ['Ergonomics', 'Soldering', 'Random', 'Welding'], answer: 'Ergonomics', explanation: 'Designing for humans.', difficulty: 'intermediate' },
            { qtype: 'brain_teaser', prompt: 'Make one stand that works for both portrait and landscape. What feature is needed?', answer: 'A lip/groove that supports both orientations or an adjustable angle.', explanation: 'Flexible support.', difficulty: 'advanced' },
            { qtype: 'tinkering', prompt: 'Add a feature so the stand also amplifies the phone speaker. How?', answer: 'Open-ended', explanation: 'A horn-shaped channel near the speaker.', difficulty: 'advanced' },
          ],
        },
      ],
    },
    {
      title: 'Design & Entrepreneurial Thinking',
      slug: 'design-thinking',
      icon: '💡',
      color: '#ffd166',
      description: 'Apply design thinking to real social problems.',
      chapters: [
        {
          title: 'Design a Room for the Elderly',
          difficulty: 'advanced', est: 60,
          summary: 'Use empathy and design thinking to make a safe, comfortable room for senior citizens.',
          hook: 'Could a small change in a room prevent a dangerous fall for your grandparents? Designers think about exactly this.',
          layman: 'Older people may have weak eyes, joints or balance. Designing their room means thinking about their needs: good lighting, grab bars, no slippery floors, easy-to-reach things. Empathy turns into safety.',
          concept: 'Inclusive/universal design creates spaces usable by everyone, including people with reduced mobility or vision. It starts with empathy and ends with practical safety features.',
          howItWorks: [
            'Empathize: list challenges (poor sight, weak knees, slow reactions).',
            'Define: “A room that prevents falls and is easy to use.”',
            'Ideate: grab bars, night lights, anti-slip mats, low shelves.',
            'Prototype: sketch/model the room layout.',
            'Test: check each feature against a real need.',
          ],
          realWorld: [
            'Hospital and old-age-home room design.',
            'Wheelchair ramps and accessible toilets.',
            'Smart fall-detection devices.',
          ],
          logic: 'Mapping each user need to a specific feature is requirements thinking — the same skill used to plan software features from user stories.',
          steps: [
            'Interview an elderly person about daily difficulties.',
            'Write a problem statement.',
            'Brainstorm 8+ features for safety/comfort.',
            'Sketch the room layout with features placed.',
            'Justify each feature with the need it solves.',
          ],
          diagram: 'design_thinking',
          facts: [
            'Falls are a leading cause of injury for the elderly.',
            'Good contrast and lighting greatly help weak eyesight.',
            'Universal design helps everyone, not just the elderly.',
          ],
          questions: [
            { qtype: 'mcq', prompt: 'Designing a space safe for everyone including the disabled is called?', options: ['Universal/inclusive design', 'Random design', 'Luxury design', 'No design'], answer: 'Universal/inclusive design', explanation: 'Usable by all.', difficulty: 'beginner' },
            { qtype: 'oneliner', prompt: 'One line: which design stage means understanding the user’s difficulties?', answer: 'Empathize.', explanation: 'First stage.', difficulty: 'beginner' },
            { qtype: 'logical', prompt: 'Matching each need to a feature is?', options: ['Requirements thinking', 'Soldering', 'Guessing', 'Painting'], answer: 'Requirements thinking', explanation: 'Need → feature.', difficulty: 'advanced' },
            { qtype: 'brain_teaser', prompt: 'An elderly person forgets to switch off the gas. Design a non-scary safety solution.', answer: 'Auto gas cut-off with a gentle reminder light/alarm.', explanation: 'Automate safety.', difficulty: 'advanced' },
            { qtype: 'tinkering', prompt: 'Design a bedside device that helps someone with weak hands call for help. Describe it.', answer: 'Open-ended', explanation: 'Large button + alert.', difficulty: 'advanced' },
          ],
        },
        {
          title: 'Final Project: Ensure Water Conservation',
          difficulty: 'advanced', est: 60,
          summary: 'Apply everything you learned to design a solution that saves water in your community.',
          hook: 'Clean water is precious and running out. Can your tinkering skills help save every drop?',
          layman: 'Water conservation means using less and wasting less water. You will combine sensors, design thinking and creativity to build a solution — like a tap that shuts when not needed, or a tank that warns when full.',
          concept: 'A real engineering project combines multiple skills: identify the problem, measure it (data), design a solution (electronics/mechanics), prototype and test — a full innovation cycle.',
          howItWorks: [
            'Identify where water is wasted (taps, tanks, irrigation).',
            'Measure or estimate the waste (data).',
            'Choose a tech solution (sensor auto-tap, overflow alarm, drip system).',
            'Prototype it and test how much water it saves.',
            'Plan how to scale it to the whole community.',
          ],
          realWorld: [
            'Automatic taps in airports and malls.',
            'Drip irrigation on farms.',
            'Rainwater harvesting systems.',
          ],
          logic: 'Combining sensing, decision logic and action to meet a goal under real constraints is full systems engineering — and measuring the saving makes it data-driven.',
          steps: [
            'Pick one water-waste problem to solve.',
            'Collect data on current usage/waste.',
            'Design a prototype solution (sensor/mechanism).',
            'Build and test; record water saved.',
            'Present results and a scaling plan.',
          ],
          diagram: 'sensor',
          facts: [
            'A dripping tap can waste thousands of litres a year.',
            'Drip irrigation can cut farm water use by up to 60%.',
            'Only about 3% of Earth’s water is fresh and usable.',
          ],
          questions: [
            { qtype: 'mcq', prompt: 'An auto-shutoff tap saves water using which idea from Class 7?', options: ['Sensors + conditional logic', 'Painting', '3D color', 'Nothing'], answer: 'Sensors + conditional logic', explanation: 'Sense hands → run water.', difficulty: 'intermediate' },
            { qtype: 'oneliner', prompt: 'One line: why measure water use before designing a fix?', answer: 'To know the real problem size and prove the saving.', explanation: 'Data-driven design.', difficulty: 'intermediate' },
            { qtype: 'logical', prompt: 'Combining sensing + decision + action to hit a goal is?', options: ['Systems engineering', 'Soldering only', 'Random', 'Painting'], answer: 'Systems engineering', explanation: 'Full system.', difficulty: 'advanced' },
            { qtype: 'brain_teaser', prompt: 'A tank overflows at night when no one notices. Design a cheap fix.', answer: 'A float sensor that triggers an alarm/auto-stop pump.', explanation: 'Sense level → act.', difficulty: 'advanced' },
            { qtype: 'tinkering', prompt: 'Design a complete smart water-saving system for your school. List its parts.', answer: 'Open-ended', explanation: 'Sensors, logic, alerts, savings tracking.', difficulty: 'advanced' },
          ],
        },
      ],
    },
  ],
};
