import { GradeSpec } from './curriculum';

export const grade8: GradeSpec = {
  number: 8,
  name: 'Class 8',
  level_label: 'ATL Tinkering Level III',
  description: 'Advanced tinkering: measurement, IoT with ESP32, robotics, woodworking and sustainability projects.',
  modules: [
    {
      title: 'Basic Electronics',
      slug: 'basic-electronics',
      icon: '⚡',
      color: '#f72585',
      description: 'Measure, display and sense with real electronic tools.',
      chapters: [
        {
          title: "Ohm's Law and How to Use a Multimeter",
          difficulty: 'intermediate', est: 60,
          summary: 'Master the V = I × R relationship and learn to measure voltage, current and resistance.',
          hook: 'How do engineers “see” invisible electricity? With one magic tool — the multimeter — and one golden rule: Ohm’s Law.',
          layman: 'Electricity has three key quantities: Voltage (the push), Current (the flow) and Resistance (the obstacle). Ohm’s Law ties them together: V = I × R. A multimeter is the device that measures all three.',
          concept: 'Ohm’s Law states that voltage equals current times resistance (V = I × R). Rearranged: I = V/R and R = V/I. A multimeter selects a mode (V, A or Ω) to measure each.',
          howItWorks: [
            'Voltage (V) is measured across a component (multimeter in parallel).',
            'Current (I) is measured through a component (multimeter in series).',
            'Resistance (Ω) is measured with power OFF.',
            'Using V = I × R you can calculate the missing third value.',
          ],
          realWorld: [
            'Electricians checking faulty wiring.',
            'Repairing gadgets and batteries.',
            'Designing safe circuits that won’t burn out.',
          ],
          logic: 'V = I × R is a mathematical model: change one variable and predict another. Modelling relationships with formulas is core computational thinking.',
          steps: [
            'Set the multimeter to the correct mode (V/A/Ω).',
            'Measure a resistor’s resistance.',
            'Measure the voltage across it in a circuit.',
            'Calculate the current with I = V/R and verify by measuring.',
          ],
          code: { language: 'text', code: 'V = I × R\nI = V / R\nR = V / I', note: 'Rearrange to find any unknown quantity.' },
          diagram: 'ohm',
          facts: [
            'Ohm’s Law is named after German physicist Georg Ohm (1827).',
            'Measuring current requires breaking the circuit and going in series.',
            'Resistance is measured in ohms (Ω).',
          ],
          questions: [
            { qtype: 'mcq', prompt: 'Ohm’s Law is written as?', options: ['V = I + R', 'V = I × R', 'V = I − R', 'V = I / R'], answer: 'V = I × R', explanation: 'Voltage = current × resistance.', difficulty: 'beginner' },
            { qtype: 'mcq', prompt: 'To measure current, the multimeter is connected in?', options: ['Parallel', 'Series', 'Reverse', 'Nowhere'], answer: 'Series', explanation: 'Current flows through it.', difficulty: 'intermediate' },
            { qtype: 'computational', prompt: 'If V = 10V and R = 5Ω, what is the current I?', options: ['2 A', '50 A', '5 A', '0.5 A'], answer: '2 A', explanation: 'I = V/R = 10/5 = 2A.', difficulty: 'intermediate' },
            { qtype: 'computational', prompt: 'If I = 0.5A through R = 100Ω, what is V?', options: ['50V', '100V', '0.005V', '200V'], answer: '50V', explanation: 'V = I×R = 0.5×100 = 50V.', difficulty: 'advanced' },
            { qtype: 'oneliner', prompt: 'One line: what should be OFF when measuring resistance?', answer: 'The power/circuit must be switched off.', explanation: 'Avoid false readings/damage.', difficulty: 'intermediate' },
            { qtype: 'brain_teaser', prompt: 'Keeping voltage fixed, you double the resistance. What happens to current and why?', answer: 'Current halves, because I = V/R.', explanation: 'Inverse relationship.', difficulty: 'advanced' },
            { qtype: 'tinkering', prompt: 'Plan an experiment to verify Ohm’s Law using 3 different resistors. What will you record?', answer: 'Open-ended', explanation: 'Record V and I, check V/I is constant per resistor.', difficulty: 'advanced' },
          ],
        },
        {
          title: '7 Segment Display',
          difficulty: 'intermediate', est: 60,
          summary: 'Learn how digital numbers are formed by lighting up seven LED bars.',
          hook: 'How does a digital clock draw the number 8 with just a few glowing sticks? Crack the code of the 7-segment display!',
          layman: 'A 7-segment display has seven LED bars arranged like the number 8. By turning the right bars on and off, you can show any digit 0–9. It is how clocks, meters and scoreboards show numbers.',
          concept: 'Each of the 7 segments (a–g) is an LED. A digit is just a specific pattern of ON/OFF segments. This is binary thinking: each segment is a 1 (on) or 0 (off).',
          howItWorks: [
            'Seven LEDs labelled a–g form the figure-8 shape.',
            'To show “7”, light segments a, b, c (top + right side).',
            'Common-cathode types share the negative; common-anode share positive.',
            'A microcontroller sets the on/off pattern for each digit.',
          ],
          realWorld: [
            'Digital clocks and microwave timers.',
            'Calculators and electricity meters.',
            'Scoreboards and lift floor indicators.',
          ],
          logic: 'Representing each digit as a 7-bit ON/OFF pattern is binary encoding — the same idea computers use to store everything as 1s and 0s.',
          steps: [
            'Identify the 7 segments a–g and the common pin.',
            'Light single segments to learn their positions.',
            'Create the pattern for digits 0, 1 and 8.',
            'Drive it from an Arduino with a lookup table.',
          ],
          code: { language: 'text', code: 'Digit 0 -> a b c d e f   (g off)\nDigit 1 -> b c\nDigit 7 -> a b c\nDigit 8 -> a b c d e f g (all on)', note: 'Each digit = a pattern of ON segments.' },
          diagram: 'flow',
          facts: [
            'The “8” uses all seven segments — the most LEDs of any digit.',
            'Adding a dot (DP) makes it 8 segments for decimals.',
            '7-segment displays appeared in the 1970s on early calculators.',
          ],
          questions: [
            { qtype: 'mcq', prompt: 'How many LED segments form the figure-8 (excluding dot)?', options: ['5', '7', '8', '10'], answer: '7', explanation: 'Segments a–g.', difficulty: 'beginner' },
            { qtype: 'mcq', prompt: 'Which digit lights ALL seven segments?', options: ['1', '7', '8', '4'], answer: '8', explanation: 'Full figure-8.', difficulty: 'beginner' },
            { qtype: 'oneliner', prompt: 'One line: each segment being on/off is an example of which number system?', answer: 'Binary (1 = on, 0 = off).', explanation: 'Two states.', difficulty: 'intermediate' },
            { qtype: 'computational', prompt: 'To show “7” you light segments a, b and c. How many segments stay OFF?', options: ['3', '4', '7', '0'], answer: '4', explanation: '7 total − 3 on = 4 off.', difficulty: 'intermediate' },
            { qtype: 'logical', prompt: 'Storing each digit as a 7-bit pattern is called?', options: ['Binary encoding', 'Soldering', 'Random', 'Painting'], answer: 'Binary encoding', explanation: 'On/off bits.', difficulty: 'advanced' },
            { qtype: 'brain_teaser', prompt: 'How could you show letters like A, b, C, d, E, F on a 7-segment display?', answer: 'Light segment patterns that resemble those letters (used in hex displays).', explanation: 'Creative patterns.', difficulty: 'advanced' },
            { qtype: 'tinkering', prompt: 'Design a dice that shows 1–6 on a 7-segment display when a button is pressed. Outline the logic.', answer: 'Open-ended', explanation: 'Random number → pattern.', difficulty: 'advanced' },
          ],
        },
        {
          title: 'PCB Etching',
          difficulty: 'advanced', est: 60,
          summary: 'Turn a circuit design into a real printed circuit board by etching away copper.',
          hook: 'Inside every gadget is a green board with shiny copper lines. How are those precise tracks made? By etching!',
          layman: 'A PCB (Printed Circuit Board) replaces messy wires with neat copper “roads” printed on a board. Etching means using a chemical to dissolve the unwanted copper, leaving only your circuit tracks behind.',
          concept: 'You protect the wanted copper tracks with a mask (ink/toner) and dip the board in an etchant. The exposed copper dissolves; the masked copper remains as your circuit. Safety with chemicals is essential.',
          howItWorks: [
            'Design the circuit layout (tracks connecting components).',
            'Transfer the design onto the copper board as a protective mask.',
            'Dip in etchant (e.g., ferric chloride) — exposed copper dissolves.',
            'Clean off the mask, drill holes and solder components.',
          ],
          realWorld: [
            'Every phone, TV and computer has PCBs inside.',
            'Hobby electronics and custom robotics boards.',
            'Industrial control systems.',
          ],
          logic: 'A PCB layout is a planning/optimization puzzle: connect all parts with non-crossing tracks in minimum space — like solving a graph routing problem.',
          steps: [
            'Draw the track layout on paper or software.',
            'Transfer it as a mask onto the copper board.',
            'Etch carefully with gloves and goggles.',
            'Rinse, drill and solder the components.',
          ],
          diagram: 'flow',
          facts: [
            'PCB stands for Printed Circuit Board.',
            'Ferric chloride etchant must be handled with gloves and care.',
            'Multi-layer PCBs can stack 10+ copper layers.',
          ],
          questions: [
            { qtype: 'mcq', prompt: 'Etching removes which material to leave the circuit tracks?', options: ['Plastic', 'Unwanted copper', 'Glass', 'Solder'], answer: 'Unwanted copper', explanation: 'Etchant dissolves exposed copper.', difficulty: 'beginner' },
            { qtype: 'mcq', prompt: 'PCB stands for?', options: ['Printed Circuit Board', 'Power Control Box', 'Plastic Copper Bar', 'Public Circuit Board'], answer: 'Printed Circuit Board', explanation: 'Definition.', difficulty: 'beginner' },
            { qtype: 'oneliner', prompt: 'One line: why wear gloves and goggles during etching?', answer: 'The etchant chemical is corrosive and harmful to skin/eyes.', explanation: 'Safety first.', difficulty: 'intermediate' },
            { qtype: 'logical', prompt: 'Connecting all parts with non-crossing tracks in least space is like solving a?', options: ['Routing/graph problem', 'Painting', 'Random task', 'Cooking'], answer: 'Routing/graph problem', explanation: 'Optimization.', difficulty: 'advanced' },
            { qtype: 'brain_teaser', prompt: 'Two tracks must cross but copper can’t overlap on one layer. How do real PCBs solve this?', answer: 'Use a jumper or a second copper layer with a via.', explanation: 'Multi-layer routing.', difficulty: 'advanced' },
            { qtype: 'tinkering', prompt: 'Plan a tiny PCB for an LED + resistor + battery. Sketch the track layout.', answer: 'Open-ended', explanation: 'Minimal single-loop layout.', difficulty: 'advanced' },
          ],
        },
        {
          title: 'Sensors and Actuators using Arduino',
          difficulty: 'advanced', est: 60,
          summary: 'Connect sensors (input) and actuators (output) to Arduino to build a reactive system.',
          hook: 'A robot that senses the world and acts on it feels alive. Sensors are its senses, actuators are its muscles!',
          layman: 'A sensor measures something (temperature, distance, light) and tells the Arduino. An actuator is something the Arduino moves or activates (motor, buzzer, servo). Together: sense → think → act.',
          concept: 'Sensors are inputs that convert physical quantities to electrical signals; actuators are outputs that convert signals to physical action. The Arduino is the decision-maker linking them.',
          howItWorks: [
            'A sensor (e.g., ultrasonic) sends data to an Arduino input pin.',
            'The Arduino code reads it and applies logic.',
            'Based on the decision, it drives an actuator (servo/motor/buzzer).',
            'This forms a closed sense–decide–act loop.',
          ],
          realWorld: [
            'Automatic doors (motion sensor + motor).',
            'Reverse parking sensors (distance + buzzer).',
            'Smart thermostats (temperature + heater).',
          ],
          logic: 'The sense–decide–act loop is the basic architecture of robots and AI agents: perceive the environment, reason, then take action.',
          steps: [
            'Wire a sensor to an input pin and an actuator to an output pin.',
            'Read the sensor value in loop().',
            'Use if/else to decide an action.',
            'Drive the actuator; test by changing the sensor input.',
          ],
          code: {
            language: 'cpp',
            code: 'int dist = readUltrasonic();\nif (dist < 20) {       // object close\n  buzzer(HIGH);        // actuator on\n} else {\n  buzzer(LOW);\n}',
            note: 'Sense (read) → decide (if) → act (buzzer).',
          },
          diagram: 'sensor',
          facts: [
            'An ultrasonic sensor measures distance using sound echoes — like a bat.',
            'A servo motor moves to an exact angle on command.',
            'Robots are basically sensors + actuators + code.',
          ],
          questions: [
            { qtype: 'mcq', prompt: 'A sensor is a(n) ____ and an actuator is a(n) ____.', options: ['output, input', 'input, output', 'both inputs', 'both outputs'], answer: 'input, output', explanation: 'Sense vs act.', difficulty: 'beginner' },
            { qtype: 'mcq', prompt: 'Which is an actuator?', options: ['Ultrasonic sensor', 'Servo motor', 'LDR', 'Thermometer'], answer: 'Servo motor', explanation: 'It produces motion.', difficulty: 'beginner' },
            { qtype: 'oneliner', prompt: 'One line: name the loop sensors+actuators+code create.', answer: 'The sense–decide–act loop.', explanation: 'Robot architecture.', difficulty: 'intermediate' },
            { qtype: 'logical', prompt: 'A reverse-parking beeper uses which pair?', options: ['Distance sensor + buzzer', 'Two buzzers', 'Two sensors', 'No parts'], answer: 'Distance sensor + buzzer', explanation: 'Input + output.', difficulty: 'intermediate' },
            { qtype: 'computational', prompt: 'Code beeps when dist < 20. Will it beep at dist = 15?', options: ['Yes', 'No'], answer: 'Yes', explanation: '15 < 20 is true.', difficulty: 'beginner' },
            { qtype: 'brain_teaser', prompt: 'A robot must slow down (not just stop) as it nears a wall. How do you change the logic?', answer: 'Map distance to speed (smaller distance → slower) instead of on/off.', explanation: 'Proportional control.', difficulty: 'advanced' },
            { qtype: 'tinkering', prompt: 'Design an automatic hand-sanitizer dispenser with Arduino. List sensor + actuator.', answer: 'Open-ended', explanation: 'IR sensor + pump motor.', difficulty: 'advanced' },
          ],
        },
      ],
    },
    {
      title: 'Internet of Things (IoT)',
      slug: 'iot',
      icon: '🌐',
      color: '#4cc9f0',
      description: 'Connect devices to the internet and control them from anywhere.',
      chapters: [
        {
          title: 'ESP32 Basics',
          difficulty: 'intermediate', est: 60,
          summary: 'Meet the ESP32 — an Arduino-like board with built-in Wi-Fi and Bluetooth.',
          hook: 'What if your project could connect to the internet and be controlled from your phone across the world? Say hello to the ESP32!',
          layman: 'The ESP32 is like an Arduino with super-powers: it has Wi-Fi and Bluetooth built in. This lets your projects send data to the cloud and receive commands from a phone or website — the heart of IoT.',
          concept: 'IoT (Internet of Things) means everyday devices connect to the internet to share data and be controlled remotely. The ESP32 is a low-cost Wi-Fi microcontroller perfect for this.',
          howItWorks: [
            'The ESP32 runs your code like an Arduino (setup/loop).',
            'It connects to a Wi-Fi network using an SSID and password.',
            'It can host a web server or send data to a cloud service.',
            'Your phone/browser communicates with it over the network.',
          ],
          realWorld: [
            'Smart bulbs and plugs controlled by an app.',
            'Weather stations uploading data to the cloud.',
            'Smart door locks and home automation.',
          ],
          logic: 'IoT introduces client–server thinking: one device requests, another responds. Understanding this communication model underpins all networked computing.',
          steps: [
            'Install ESP32 board support in the Arduino IDE.',
            'Enter your Wi-Fi SSID and password in code.',
            'Upload a sketch that connects and prints its IP address.',
            'Open that IP in a browser to see a simple page.',
          ],
          code: {
            language: 'cpp',
            code: '#include <WiFi.h>\nvoid setup(){\n  Serial.begin(115200);\n  WiFi.begin("MY_SSID", "MY_PASSWORD");\n  while (WiFi.status() != WL_CONNECTED) delay(500);\n  Serial.println(WiFi.localIP()); // device IP\n}\nvoid loop(){}',
            note: 'Once connected, the ESP32 gets an IP address on your network.',
          },
          diagram: 'iot',
          facts: [
            'The ESP32 has two CPU cores and built-in Wi-Fi + Bluetooth.',
            'There are tens of billions of IoT devices in the world today.',
            'An IP address is like a postal address for a device on a network.',
          ],
          questions: [
            { qtype: 'mcq', prompt: 'The ESP32’s key advantage over a basic Arduino Uno is?', options: ['It is bigger', 'Built-in Wi-Fi & Bluetooth', 'It needs no code', 'It has no pins'], answer: 'Built-in Wi-Fi & Bluetooth', explanation: 'Wireless connectivity.', difficulty: 'beginner' },
            { qtype: 'mcq', prompt: 'IoT stands for?', options: ['Internet of Things', 'Input or Test', 'Internal Output Tool', 'Image of Type'], answer: 'Internet of Things', explanation: 'Definition.', difficulty: 'beginner' },
            { qtype: 'oneliner', prompt: 'One line: what is an IP address?', answer: 'A unique address that identifies a device on a network.', explanation: 'Like a postal address.', difficulty: 'intermediate' },
            { qtype: 'logical', prompt: 'A phone asking the ESP32 for data is an example of?', options: ['Client–server communication', 'Soldering', 'Random', 'Etching'], answer: 'Client–server communication', explanation: 'Request/response.', difficulty: 'advanced' },
            { qtype: 'brain_teaser', prompt: 'Your ESP32 keeps disconnecting from Wi-Fi. List two possible causes.', answer: 'Weak signal/distance, wrong password, or power issues.', explanation: 'Debug connectivity.', difficulty: 'advanced' },
            { qtype: 'tinkering', prompt: 'Plan an IoT doorbell that sends a message to your phone when pressed. Outline the parts.', answer: 'Open-ended', explanation: 'Button + ESP32 + cloud notification.', difficulty: 'advanced' },
          ],
        },
        {
          title: 'Interfacing LDR with ESP32',
          difficulty: 'intermediate', est: 60,
          summary: 'Read a light sensor with the ESP32 and send the reading over Wi-Fi.',
          hook: 'Imagine checking the brightness of your room from your phone miles away. Connect an LDR to the ESP32 and you can!',
          layman: 'You connect an LDR (light sensor) to the ESP32’s analog pin. The ESP32 reads how bright it is as a number and can show it on a web page — so you monitor light remotely.',
          concept: 'Analog inputs read a range of values (not just on/off). The ESP32’s ADC (Analog-to-Digital Converter) turns the LDR’s voltage into a number your code can use and share online.',
          howItWorks: [
            'The LDR + resistor form a voltage divider feeding an analog pin.',
            'analogRead() converts the voltage to a number (e.g., 0–4095).',
            'Brighter light changes the voltage and thus the number.',
            'The ESP32 serves this value on a web page or to the cloud.',
          ],
          realWorld: [
            'Smart blinds that adjust to sunlight.',
            'Automatic display brightness.',
            'Remote greenhouse light monitoring.',
          ],
          logic: 'Analog → digital conversion is sampling: turning continuous reality into numbers a computer can process. It is how all sensors, audio and images enter the digital world.',
          steps: [
            'Wire the LDR voltage divider to an ESP32 analog pin.',
            'Use analogRead() to get the light value.',
            'Print it to Serial to test.',
            'Serve the value on a simple web page.',
          ],
          code: {
            language: 'cpp',
            code: 'int ldrPin = 34;\nvoid setup(){ Serial.begin(115200); }\nvoid loop(){\n  int light = analogRead(ldrPin); // 0..4095\n  Serial.println(light);\n  delay(500);\n}',
            note: 'analogRead returns a number representing brightness.',
          },
          diagram: 'iot',
          facts: [
            'The ESP32 ADC gives values from 0 to 4095 (12-bit).',
            'Turning analog signals into numbers is called sampling.',
            'A voltage divider converts resistance change into a measurable voltage.',
          ],
          questions: [
            { qtype: 'mcq', prompt: 'analogRead() on ESP32 returns a value in roughly what range?', options: ['0–1', '0–255', '0–4095', '0–10'], answer: '0–4095', explanation: '12-bit ADC.', difficulty: 'intermediate' },
            { qtype: 'mcq', prompt: 'Converting an analog voltage to a number is done by the?', options: ['LED', 'ADC', 'Battery', 'Motor'], answer: 'ADC', explanation: 'Analog-to-Digital Converter.', difficulty: 'beginner' },
            { qtype: 'oneliner', prompt: 'One line: what does the LDR + resistor pair create?', answer: 'A voltage divider that the ESP32 can read.', explanation: 'Resistance → voltage.', difficulty: 'intermediate' },
            { qtype: 'logical', prompt: 'Turning continuous light into discrete numbers is called?', options: ['Sampling', 'Soldering', 'Painting', 'Etching'], answer: 'Sampling', explanation: 'Analog to digital.', difficulty: 'advanced' },
            { qtype: 'computational', prompt: 'In bright light value = 3000, in dark = 200. Which is brighter: 2500 or 800?', options: ['2500', '800'], answer: '2500', explanation: 'Higher value = brighter here.', difficulty: 'beginner' },
            { qtype: 'brain_teaser', prompt: 'Readings jump around even with steady light. How do you get a stable value?', answer: 'Average several readings (filtering/smoothing).', explanation: 'Reduce noise.', difficulty: 'advanced' },
            { qtype: 'tinkering', prompt: 'Design a system that emails you if your room is dark after sunrise. Outline it.', answer: 'Open-ended', explanation: 'Threshold + cloud alert.', difficulty: 'advanced' },
          ],
        },
        {
          title: 'Control an LED using a Mobile App',
          difficulty: 'advanced', est: 60,
          summary: 'Turn an LED on/off from your phone over Wi-Fi using the ESP32 as a web server.',
          hook: 'Flip a switch in your hand and a light obeys across the room — no wires. Let’s build true remote control!',
          layman: 'The ESP32 hosts a tiny web page with ON and OFF buttons. Your phone opens this page over Wi-Fi; tapping a button sends a command to the ESP32, which switches the LED. This is home automation in miniature.',
          concept: 'A web server listens for requests. The phone (client) sends a request like /on or /off; the server reads it and acts. This request–response model powers the entire web.',
          howItWorks: [
            'The ESP32 connects to Wi-Fi and starts a web server.',
            'It serves a page with ON/OFF buttons (links to /on and /off).',
            'Tapping a button sends an HTTP request to the ESP32.',
            'The ESP32 reads the request path and sets the LED accordingly.',
          ],
          realWorld: [
            'Smart-home apps controlling lights and fans.',
            'Industrial remote machine control.',
            'Smart agriculture controlling pumps.',
          ],
          logic: 'Mapping a URL/command to an action is exactly how APIs work. Every app you use talks to servers using this request→action pattern.',
          steps: [
            'Connect the ESP32 to Wi-Fi and an LED to a pin.',
            'Start a web server that serves ON/OFF buttons.',
            'Handle /on and /off requests to switch the LED.',
            'Open the ESP32’s IP on your phone and control the LED.',
          ],
          code: {
            language: 'cpp',
            code: '// On request "/on":  digitalWrite(led, HIGH);\n// On request "/off": digitalWrite(led, LOW);\n// Serve buttons:\n// <a href="/on">ON</a>  <a href="/off">OFF</a>',
            note: 'The browser link path tells the ESP32 what to do.',
          },
          diagram: 'iot',
          facts: [
            'HTTP is the language phones and servers use to talk.',
            'The ESP32 can be both a Wi-Fi client and a web server.',
            'A request path like /on is how the command is sent.',
          ],
          questions: [
            { qtype: 'mcq', prompt: 'The phone tapping a button sends a(n) ____ to the ESP32.', options: ['email', 'HTTP request', 'photo', 'sound'], answer: 'HTTP request', explanation: 'Web request.', difficulty: 'beginner' },
            { qtype: 'mcq', prompt: 'In this setup the ESP32 acts as the?', options: ['Client', 'Web server', 'Battery', 'Sensor'], answer: 'Web server', explanation: 'It serves the page and handles requests.', difficulty: 'intermediate' },
            { qtype: 'oneliner', prompt: 'One line: what model powers phone↔server communication?', answer: 'The request–response model.', explanation: 'Ask and answer.', difficulty: 'intermediate' },
            { qtype: 'logical', prompt: 'Mapping a URL like /on to “turn LED on” is the idea behind?', options: ['APIs', 'Soldering', 'Painting', 'Etching'], answer: 'APIs', explanation: 'Command → action.', difficulty: 'advanced' },
            { qtype: 'brain_teaser', prompt: 'Anyone on the Wi-Fi can toggle your LED. How would you add basic security?', answer: 'Require a password/token before accepting commands.', explanation: 'Authentication.', difficulty: 'advanced' },
            { qtype: 'tinkering', prompt: 'Extend the app to also show the LED’s current state. How?', answer: 'Open-ended', explanation: 'Server reports state on the page.', difficulty: 'advanced' },
          ],
        },
        {
          title: 'IoT Plant Monitoring using ESP32',
          difficulty: 'advanced', est: 60,
          summary: 'Build a smart system that monitors soil moisture and alerts you when plants need water.',
          hook: 'What if your plants could text you “I’m thirsty!”? Build an IoT gardener that never forgets to water!',
          layman: 'A soil moisture sensor measures how wet the soil is. The ESP32 reads it and, if the soil is too dry, sends an alert to your phone or even turns on a water pump. Your plants get cared for automatically.',
          concept: 'This combines sensing (moisture), thresholds (decision), networking (alerts) and actuation (pump) into a complete IoT system — the full smart-device pipeline.',
          howItWorks: [
            'A moisture sensor reads soil wetness as a number.',
            'The ESP32 compares it to a threshold.',
            'If too dry, it sends a notification/uploads data to the cloud.',
            'Optionally it switches on a small water pump (actuator).',
          ],
          realWorld: [
            'Smart farming and precision agriculture.',
            'Automated home garden systems.',
            'Greenhouse climate control.',
          ],
          logic: 'Threshold-based decisions plus data logging let you spot trends over time — the basis of data-driven automation and predictive maintenance.',
          steps: [
            'Insert the moisture sensor into the soil and wire it to the ESP32.',
            'Read and calibrate the dry/wet values.',
            'Set a threshold for “needs water”.',
            'Send an alert (and optionally trigger a pump) when dry.',
          ],
          code: {
            language: 'cpp',
            code: 'int moisture = analogRead(35);\nif (moisture < DRY_THRESHOLD) {\n  sendAlert("Plant needs water!");\n  // pump(HIGH);\n}',
            note: 'Calibrate DRY_THRESHOLD for your soil and sensor.',
          },
          diagram: 'iot',
          facts: [
            'Smart irrigation can cut water use dramatically.',
            'Over-watering can harm plants as much as under-watering.',
            'Logging data over days reveals watering patterns.',
          ],
          questions: [
            { qtype: 'mcq', prompt: 'The plant monitor primarily senses?', options: ['Sound', 'Soil moisture', 'Color', 'Speed'], answer: 'Soil moisture', explanation: 'Moisture sensor.', difficulty: 'beginner' },
            { qtype: 'mcq', prompt: 'A decision like “if dry then alert” uses a?', options: ['Threshold', 'Battery', 'Paint', 'Gear'], answer: 'Threshold', explanation: 'Compare to a limit.', difficulty: 'beginner' },
            { qtype: 'oneliner', prompt: 'One line: why calibrate the sensor first?', answer: 'So the dry/wet numbers match real soil conditions.', explanation: 'Accurate thresholds.', difficulty: 'intermediate' },
            { qtype: 'logical', prompt: 'Recording moisture over many days helps you?', options: ['Spot watering trends', 'Solder faster', 'Paint plants', 'Nothing'], answer: 'Spot watering trends', explanation: 'Data-driven insight.', difficulty: 'advanced' },
            { qtype: 'computational', prompt: 'Threshold is 1500; dry reads higher. Soil reads 1800. Does it need water?', options: ['Yes', 'No'], answer: 'Yes', explanation: '1800 > 1500 = dry.', difficulty: 'intermediate' },
            { qtype: 'brain_teaser', prompt: 'The pump sometimes runs forever if the sensor fails. How do you make it fail-safe?', answer: 'Add a max run-time limit and sensor sanity checks.', explanation: 'Safety limits.', difficulty: 'advanced' },
            { qtype: 'tinkering', prompt: 'Design a full smart garden: moisture, light and temperature with one dashboard. List parts.', answer: 'Open-ended', explanation: 'Multiple sensors + cloud dashboard.', difficulty: 'advanced' },
          ],
        },
      ],
    },
    {
      title: '3D Design & Printing',
      slug: '3d-design-printing',
      icon: '🧊',
      color: '#4361ee',
      description: 'Design functional tools and moving robots.',
      chapters: [
        {
          title: 'Design a Spanner and 3D Print It',
          difficulty: 'intermediate', est: 60,
          summary: 'Model a working spanner/wrench and learn about tolerances and strength.',
          hook: 'Can a plastic tool actually turn a real bolt? Design a spanner with the right fit and find out!',
          layman: 'A spanner grips a nut/bolt to turn it. The opening must match the bolt size exactly — too big and it slips, too small and it won’t fit. You will design the jaw and handle and learn about “tolerance”.',
          concept: 'Tolerance is the small allowed difference between the design size and real size so parts fit. The handle length gives leverage (torque) to turn tight bolts.',
          howItWorks: [
            'Measure the bolt’s width across flats.',
            'Design the jaw opening slightly larger by a tolerance gap.',
            'A longer handle gives more turning force (torque).',
            'Thicker material resists bending under load.',
          ],
          realWorld: [
            'Everyday tools in every toolbox.',
            'Custom tools printed for special parts.',
            'Tools printed in space stations.',
          ],
          logic: 'Tolerance is about precision under uncertainty — accounting for real-world variation, a key engineering and quality-control concept.',
          steps: [
            'Measure or pick a bolt size (e.g., 10 mm).',
            'Design the jaw opening with a small tolerance gap.',
            'Add a long, thick handle for leverage.',
            'Export STL; consider print orientation for strength.',
          ],
          diagram: 'cube3d',
          facts: [
            'Torque = force × distance, so a longer handle turns tighter bolts.',
            'Print layers can be a weak point — orientation matters for strength.',
            'Tolerance is why nuts and bolts from different makers still fit.',
          ],
          questions: [
            { qtype: 'mcq', prompt: 'The small allowed size difference so parts fit is called?', options: ['Tolerance', 'Color', 'Voltage', 'Torque'], answer: 'Tolerance', explanation: 'Fit allowance.', difficulty: 'beginner' },
            { qtype: 'mcq', prompt: 'A longer spanner handle gives more?', options: ['Color', 'Torque (turning force)', 'Weight only', 'Light'], answer: 'Torque (turning force)', explanation: 'Torque = force × distance.', difficulty: 'beginner' },
            { qtype: 'oneliner', prompt: 'One line: what happens if the jaw is too big for the bolt?', answer: 'The spanner slips and can’t turn the bolt.', explanation: 'Poor fit.', difficulty: 'intermediate' },
            { qtype: 'computational', prompt: 'Doubling the handle length (same force) changes torque by?', options: ['×0.5', '×2', '×1', '×0'], answer: '×2', explanation: 'Torque ∝ distance.', difficulty: 'advanced' },
            { qtype: 'logical', prompt: 'Accounting for real-world size variation when designing is?', options: ['Precision/quality control', 'Painting', 'Random', 'Etching'], answer: 'Precision/quality control', explanation: 'Tolerance thinking.', difficulty: 'advanced' },
            { qtype: 'brain_teaser', prompt: 'Your plastic spanner snaps at the jaw. Give two design fixes (no material change).', answer: 'Thicken the jaw and reorient print layers to the load.', explanation: 'Geometry + orientation.', difficulty: 'advanced' },
            { qtype: 'tinkering', prompt: 'Design an adjustable spanner that fits multiple bolt sizes. How would it adjust?', answer: 'Open-ended', explanation: 'Sliding jaw mechanism.', difficulty: 'advanced' },
          ],
        },
        {
          title: 'Design a Walking Robot and 3D Print It',
          difficulty: 'advanced', est: 60,
          summary: 'Create a legged robot mechanism that converts motor spin into walking motion.',
          hook: 'Wheels are easy — but legs can climb stairs and rough ground. How do you make plastic legs walk?',
          layman: 'A walking robot uses a clever linkage (like the Klann or Jansen mechanism) that turns a spinning motor into a stepping motion. You design the leg linkages so circular motion becomes a walking gait.',
          concept: 'A linkage mechanism converts rotary motion (motor) into a specific path (a foot that lifts, steps forward, and pushes back). Legs let robots handle terrain wheels cannot.',
          howItWorks: [
            'A motor rotates a crank continuously.',
            'Connected linkage bars translate this into a walking foot path.',
            'Multiple legs are timed so some push while others lift.',
            'The body moves forward step by step.',
          ],
          realWorld: [
            'Search-and-rescue robots on rubble.',
            'Boston Dynamics-style legged robots.',
            'Strandbeest wind-walking sculptures.',
          ],
          logic: 'Designing a linkage to produce a precise foot path is kinematics — predicting motion from geometry, a blend of maths, logic and creativity.',
          steps: [
            'Choose a leg linkage (e.g., Klann mechanism).',
            'Model the linkage bars with correct lengths in 3D software.',
            'Print parts and assemble with pin joints.',
            'Attach a motor crank and test the gait.',
          ],
          diagram: 'gear',
          facts: [
            'Theo Jansen’s Strandbeests “walk” using only wind and linkages.',
            'Legged robots can cross terrain wheels cannot.',
            'Tiny changes in bar length drastically change the foot path.',
          ],
          questions: [
            { qtype: 'mcq', prompt: 'A walking robot converts the motor’s rotary motion into?', options: ['Sound', 'A stepping foot path', 'Light', 'Heat'], answer: 'A stepping foot path', explanation: 'Linkage converts motion.', difficulty: 'beginner' },
            { qtype: 'mcq', prompt: 'Studying motion from the geometry of linkages is called?', options: ['Kinematics', 'Painting', 'Etching', 'Cooking'], answer: 'Kinematics', explanation: 'Motion from geometry.', difficulty: 'advanced' },
            { qtype: 'oneliner', prompt: 'One line: why time the legs so some lift while others push?', answer: 'To keep the robot balanced and moving steadily forward.', explanation: 'Gait coordination.', difficulty: 'intermediate' },
            { qtype: 'logical', prompt: 'Legs are preferred over wheels mainly for?', options: ['Rough terrain/stairs', 'Color', 'Speed on roads', 'Cost'], answer: 'Rough terrain/stairs', explanation: 'Terrain handling.', difficulty: 'intermediate' },
            { qtype: 'brain_teaser', prompt: 'Your robot walks but veers to one side. Name two likely causes.', answer: 'Unequal leg lengths/timing or uneven friction.', explanation: 'Symmetry/timing.', difficulty: 'advanced' },
            { qtype: 'tinkering', prompt: 'Design a 4-legged robot that can turn left and right. How would steering work?', answer: 'Open-ended', explanation: 'Independent side motors.', difficulty: 'advanced' },
          ],
        },
      ],
    },
    {
      title: 'Woodworking',
      slug: 'woodworking',
      icon: '🪵',
      color: '#a06a35',
      description: 'Work safely with wood and hand tools to build real objects.',
      chapters: [
        {
          title: 'Introduction to Woodworking',
          difficulty: 'beginner', est: 60,
          summary: 'Learn wood types, basic hand tools and essential workshop safety.',
          hook: 'From pencils to furniture, wood shapes our world. But the first rule of every workshop is: stay safe!',
          layman: 'Woodworking is shaping wood using tools like saws, hammers, files and drills. Different woods have different hardness. The golden rules are: measure carefully, cut slowly, and protect yourself with safety gear.',
          concept: 'Woodworking combines material knowledge (soft vs hard wood), the right tool for each job, and safety practices. “Measure twice, cut once” prevents waste and mistakes.',
          howItWorks: [
            'Choose wood: softwood (easy to cut) vs hardwood (strong, durable).',
            'Mark and measure accurately before cutting.',
            'Use the correct tool (saw to cut, file to smooth, drill to bore).',
            'Wear safety gear: goggles, gloves; keep fingers clear of blades.',
          ],
          realWorld: [
            'Furniture, doors and window frames.',
            'Toys, tool handles and sports equipment.',
            'Carpentry and construction.',
          ],
          logic: '“Measure twice, cut once” is error-prevention thinking — verifying before acting irreversibly, the same caution used before deleting data or deploying code.',
          steps: [
            'Identify a piece of softwood and hardwood.',
            'Learn the names and uses of 4 basic tools.',
            'Practice marking a straight cut line with a ruler.',
            'Review and list the safety rules.',
          ],
          diagram: 'wood',
          facts: [
            'Softwoods come from conifers; hardwoods from broadleaf trees.',
            'A hand saw cuts on the push stroke.',
            'Most workshop accidents are prevented by safety gear and focus.',
          ],
          questions: [
            { qtype: 'mcq', prompt: 'The famous woodworking safety rule is?', options: ['Cut twice, measure once', 'Measure twice, cut once', 'Never measure', 'Cut fast'], answer: 'Measure twice, cut once', explanation: 'Prevents mistakes.', difficulty: 'beginner' },
            { qtype: 'mcq', prompt: 'Which is generally easier to cut?', options: ['Hardwood', 'Softwood', 'Steel', 'Glass'], answer: 'Softwood', explanation: 'Softwood is easier.', difficulty: 'beginner' },
            { qtype: 'oneliner', prompt: 'One line: name two pieces of safety gear for woodworking.', answer: 'Safety goggles and gloves.', explanation: 'Protect eyes and hands.', difficulty: 'beginner' },
            { qtype: 'logical', prompt: '“Measure twice, cut once” teaches?', options: ['Error prevention', 'Speed over care', 'Randomness', 'Painting'], answer: 'Error prevention', explanation: 'Verify before irreversible action.', difficulty: 'advanced' },
            { qtype: 'brain_teaser', prompt: 'You must cut 10 identical pieces quickly and accurately. What technique helps?', answer: 'Use a template/jig and a stop block for repeatable cuts.', explanation: 'Jigs ensure consistency.', difficulty: 'advanced' },
            { qtype: 'tinkering', prompt: 'Design a simple jig that helps cut wood at a perfect 45° angle. Describe it.', answer: 'Open-ended', explanation: 'A mitre guide.', difficulty: 'advanced' },
          ],
        },
        {
          title: 'Make Your Own Birdhouse',
          difficulty: 'intermediate', est: 60,
          summary: 'Plan, measure, cut and assemble a wooden birdhouse — a complete woodworking project.',
          hook: 'Invite birds into your garden by building them a cozy home with your own hands!',
          layman: 'A birdhouse is a small wooden box with a roof and an entrance hole. You will plan the pieces, measure and cut them, then join them. It teaches the full make-cycle: plan → measure → cut → assemble → finish.',
          concept: 'A real build project needs a plan (cutting list with dimensions), accurate measurement, the right joints, and a weather-friendly design (sloped roof, drainage, correct hole size for the bird).',
          howItWorks: [
            'Make a cutting list: base, 2 sides, front, back, roof.',
            'Measure and cut each piece accurately.',
            'Drill an entrance hole sized for local birds.',
            'Assemble with nails/glue; add a sloped roof for rain.',
            'Add small drainage/ventilation holes.',
          ],
          realWorld: [
            'Garden birdhouses and bird feeders.',
            'Flat-pack furniture assembly logic.',
            'Any carpentry project from a plan.',
          ],
          logic: 'Breaking the build into a cutting list and ordered assembly steps is project planning and sequencing — the same as breaking a program into functions and a run order.',
          steps: [
            'Sketch the birdhouse and list all pieces with sizes.',
            'Measure and cut the pieces from wood.',
            'Drill the correctly-sized entrance hole.',
            'Assemble the box and attach a sloped roof.',
            'Sand edges and add drainage holes.',
          ],
          diagram: 'wood',
          facts: [
            'The entrance hole size decides which birds can use it.',
            'A sloped roof keeps rain out of the nest.',
            'Drainage holes stop water collecting inside.',
          ],
          questions: [
            { qtype: 'mcq', prompt: 'Why is the entrance hole size important?', options: ['Decoration', 'It decides which birds can enter (and keeps predators out)', 'For weight', 'No reason'], answer: 'It decides which birds can enter (and keeps predators out)', explanation: 'Hole size matters.', difficulty: 'beginner' },
            { qtype: 'mcq', prompt: 'A sloped roof mainly helps to?', options: ['Look nice', 'Shed rainwater', 'Add weight', 'Make sound'], answer: 'Shed rainwater', explanation: 'Water runs off.', difficulty: 'beginner' },
            { qtype: 'oneliner', prompt: 'One line: what is a cutting list?', answer: 'A list of every piece to cut with its dimensions.', explanation: 'Build plan.', difficulty: 'intermediate' },
            { qtype: 'logical', prompt: 'Splitting a build into a cutting list and ordered steps is?', options: ['Project planning/sequencing', 'Random', 'Painting', 'Etching'], answer: 'Project planning/sequencing', explanation: 'Plan + order.', difficulty: 'advanced' },
            { qtype: 'computational', prompt: 'You need 2 sides, 1 front, 1 back, 1 base, 1 roof. How many pieces total?', options: ['5', '6', '4', '7'], answer: '6', explanation: '2+1+1+1+1 = 6.', difficulty: 'beginner' },
            { qtype: 'brain_teaser', prompt: 'Rainwater still gets in despite the sloped roof. Give two fixes.', answer: 'Add roof overhang and drainage holes in the base.', explanation: 'Overhang + drainage.', difficulty: 'advanced' },
            { qtype: 'tinkering', prompt: 'Redesign the birdhouse so it can be cleaned each season. What feature do you add?', answer: 'Open-ended', explanation: 'A hinged/removable panel.', difficulty: 'advanced' },
          ],
        },
      ],
    },
    {
      title: 'Design & Entrepreneurial Thinking',
      slug: 'design-thinking',
      icon: '💡',
      color: '#ffd166',
      description: 'Design sustainable solutions for homes and communities.',
      chapters: [
        {
          title: 'Sustainable Home Model',
          difficulty: 'advanced', est: 60,
          summary: 'Design an eco-friendly home model using renewable energy, water saving and smart materials.',
          hook: 'What would a home that powers itself, saves water, and stays cool without ACs look like? Design it!',
          layman: 'A sustainable home uses less energy and water and creates less waste. Ideas include solar panels, rainwater harvesting, good ventilation, insulation and recycling. You will combine these into one model home.',
          concept: 'Sustainability means meeting today’s needs without harming the future. A sustainable home integrates renewable energy, resource efficiency, and smart design to minimise its footprint.',
          howItWorks: [
            'Solar panels generate clean electricity.',
            'Rainwater harvesting stores water for reuse.',
            'Good orientation, insulation and ventilation reduce cooling needs.',
            'Recycling and composting reduce waste.',
          ],
          realWorld: [
            'Green-rated buildings (IGBC/LEED).',
            'Passive cooling traditional architecture.',
            'Net-zero energy homes.',
          ],
          logic: 'Optimising many goals at once (energy, water, cost, comfort) is multi-objective optimization — balancing trade-offs to reach the best overall design.',
          steps: [
            'List sustainability goals for the home.',
            'Choose features for energy, water and comfort.',
            'Sketch/model the home with features placed.',
            'Explain how each feature reduces the footprint.',
          ],
          diagram: 'design_thinking',
          facts: [
            'Buildings use a large share of the world’s energy.',
            'Orientation and shade can cut cooling needs dramatically.',
            'Rainwater harvesting can supply a big part of home water needs.',
          ],
          questions: [
            { qtype: 'mcq', prompt: 'Sustainability means meeting today’s needs without?', options: ['Using any energy', 'Harming the future', 'Building homes', 'Saving water'], answer: 'Harming the future', explanation: 'Definition.', difficulty: 'beginner' },
            { qtype: 'mcq', prompt: 'Which provides clean electricity for the home?', options: ['Solar panels', 'A bigger TV', 'More lights', 'Thicker walls'], answer: 'Solar panels', explanation: 'Renewable energy.', difficulty: 'beginner' },
            { qtype: 'oneliner', prompt: 'One line: how does good ventilation help sustainability?', answer: 'It reduces the need for energy-hungry air conditioning.', explanation: 'Passive cooling.', difficulty: 'intermediate' },
            { qtype: 'logical', prompt: 'Balancing energy, water, cost and comfort together is?', options: ['Multi-objective optimization', 'Random', 'Painting', 'Etching'], answer: 'Multi-objective optimization', explanation: 'Many goals at once.', difficulty: 'advanced' },
            { qtype: 'brain_teaser', prompt: 'Solar gives day power but you need night power too. What sustainable solution helps?', answer: 'Battery storage charged during the day.', explanation: 'Store surplus energy.', difficulty: 'advanced' },
            { qtype: 'tinkering', prompt: 'Design a smart feature that automatically reduces home energy waste. Describe it.', answer: 'Open-ended', explanation: 'Sensors switching off idle devices.', difficulty: 'advanced' },
          ],
        },
        {
          title: 'Final Project: Sustainable Village Model',
          difficulty: 'advanced', est: 60,
          summary: 'Combine all your skills to design a self-sufficient, sustainable village.',
          hook: 'Scale up from one home to a whole village. Can you design a community that thrives without harming the planet?',
          layman: 'A sustainable village provides energy, clean water, food, waste management and connectivity for everyone — using renewable resources. You will combine electronics, IoT, design thinking and sustainability into one big model.',
          concept: 'This capstone integrates every module: renewable energy grids, IoT monitoring, water systems, sustainable buildings and community planning — a true systems-of-systems design.',
          howItWorks: [
            'Plan energy: shared solar/biogas with battery storage.',
            'Plan water: harvesting, filtration and smart distribution.',
            'Add IoT monitoring for water, energy and crops.',
            'Design waste management (composting, recycling).',
            'Connect it all with community-centred layout.',
          ],
          realWorld: [
            'Smart-village government initiatives.',
            'Off-grid renewable communities.',
            'Disaster-resilient settlement design.',
          ],
          logic: 'Coordinating many subsystems toward shared goals is systems-of-systems thinking — the highest level of engineering and computational planning.',
          steps: [
            'List the village’s core needs (energy, water, food, waste, connectivity).',
            'Design a solution for each using skills from Levels I–III.',
            'Integrate IoT monitoring and renewable energy.',
            'Build/sketch the village model.',
            'Present impact and a scaling/feasibility plan.',
          ],
          diagram: 'iot',
          facts: [
            'Biogas turns waste into cooking fuel and fertiliser.',
            'Micro-grids let villages share renewable energy.',
            'IoT sensors help manage scarce resources efficiently.',
          ],
          questions: [
            { qtype: 'mcq', prompt: 'A sustainable village mainly relies on?', options: ['Renewable resources', 'Only coal', 'Imported everything', 'Nothing'], answer: 'Renewable resources', explanation: 'Self-sufficient & clean.', difficulty: 'beginner' },
            { qtype: 'mcq', prompt: 'IoT sensors in the village help to?', options: ['Decorate', 'Monitor and manage resources', 'Waste power', 'Nothing'], answer: 'Monitor and manage resources', explanation: 'Smart management.', difficulty: 'intermediate' },
            { qtype: 'oneliner', prompt: 'One line: what is a micro-grid?', answer: 'A small local energy network sharing renewable power.', explanation: 'Local grid.', difficulty: 'intermediate' },
            { qtype: 'logical', prompt: 'Coordinating energy, water, waste and IoT together is?', options: ['Systems-of-systems thinking', 'Random', 'Painting', 'Etching'], answer: 'Systems-of-systems thinking', explanation: 'Highest-level design.', difficulty: 'advanced' },
            { qtype: 'brain_teaser', prompt: 'A drought hits the village. How can your design keep water flowing for weeks?', answer: 'Stored harvested water + recycling + usage limits via IoT.', explanation: 'Storage + reuse + control.', difficulty: 'advanced' },
            { qtype: 'tinkering', prompt: 'Design the complete sustainable village: list every subsystem and the tech used.', answer: 'Open-ended', explanation: 'Integrate all modules.', difficulty: 'advanced' },
          ],
        },
      ],
    },
  ],
};
